"""simplify_train_stop_unique_constraint

Revision ID: f3bfed72e013
Revises:
Create Date: 2025-06-19 12:17:39.292625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3bfed72e013'
down_revision = None  # Assuming this is the first Alembic migration for this specific area or in general if no history exists
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_train_stop_unique_with_time', 'train_stops', type_='unique')
    op.create_unique_constraint('uix_train_stop_unique_without_time', 'train_stops', ['train_id', 'train_departure_time', 'station_name', 'data_source'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_train_stop_unique_without_time', 'train_stops', type_='unique')
    op.create_unique_constraint('uix_train_stop_unique_with_time', 'train_stops', ['train_id', 'train_departure_time', 'station_name', 'data_source', 'scheduled_time'])
    # ### end Alembic commands ###
