"""
Prometheus metrics for TrackCast.

This module centralizes all Prometheus metrics definitions to avoid circular imports.
"""

from prometheus_client import Counter, Gauge, Histogram

# Model metrics
MODEL_PREDICTION_ACCURACY = Gauge(
    "model_prediction_accuracy",
    "Prediction accuracy of the model by station",
    ["station"],
)

MODEL_INFERENCE_TIME = Histogram(
    "model_inference_time_seconds",
    "Time taken to perform model inference by station",
    ["station"],
)

PREDICTIONS_GENERATED = Counter(
    "predictions_generated_total",
    "Total number of predictions generated by station",
    ["station"],
)

PREDICTION_ERRORS = Counter(
    "prediction_errors_total",
    "Total number of prediction errors by type and station",
    ["error_type", "station"],
)

# Database metrics
DB_QUERY_DURATION_SECONDS = Histogram(
    "db_query_duration_seconds", "Duration of database queries", ["query_type"]
)

# Data collection metrics
TRAINS_COLLECTED = Counter(
    "trains_collected_total",
    "Total number of trains collected by source and station",
    ["source", "station"],
)

DATA_COLLECTION_ERRORS = Counter(
    "data_collection_errors_total",
    "Total number of data collection errors by source, station, and error type",
    ["source", "station", "error_type"],
)

# Feature engineering metrics
FEATURES_PROCESSED = Counter(
    "features_processed_total",
    "Total number of features processed by station",
    ["station"],
)

FEATURE_ENGINEERING_TIME = Histogram(
    "feature_engineering_time_seconds",
    "Time taken to process features by station",
    ["station"],
)

# Train processing metrics
TRAINS_PROCESSED_TOTAL = Counter("trains_processed_total", "Total number of trains processed")

TRACK_PREDICTION_CONFIDENCE = Histogram(
    "track_prediction_confidence_ratio",
    "Distribution of track prediction confidence scores",
    ["station"],
)

# API fetch metrics
NJ_TRANSIT_FETCH_SUCCESS = Counter(
    "nj_transit_fetch_success_total", "Number of successful fetches from NJ Transit API"
)

NJ_TRANSIT_FETCH_FAILURES = Counter(
    "nj_transit_fetch_failures_total", "Number of failed fetches from NJ Transit API"
)

AMTRAK_FETCH_SUCCESS = Counter(
    "amtrak_fetch_success_total", "Number of successful fetches from Amtrak API"
)

AMTRAK_FETCH_FAILURES = Counter(
    "amtrak_fetch_failures_total", "Number of failed fetches from Amtrak API"
)

# Database connection metrics
DB_CONNECTION_POOL_UTILIZATION = Gauge(
    "db_connection_pool_utilization_ratio",
    "Ratio of active DB connections to max connections",
)
