"""add_autoincrement_to_integer_columns

Revision ID: cfecb8a3db76
Revises: 4225afa0ef51
Create Date: 2025-07-04 20:58:52.563962

"""

# revision identifiers, used by Alembic.
revision = "cfecb8a3db76"
down_revision = "4225afa0ef51"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
