"""Initial schema

Revision ID: 019443de01cd
Revises:
Create Date: 2025-07-04 17:58:26.187190

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "019443de01cd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "called_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("endpoint", sa.String(length=50), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=True),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.Column("cached", sa.Boolean(), nullable=False),
        sa.Column("error_details", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_api_calls", "api_calls", ["endpoint", "called_at"], unique=False
    )
    op.create_table(
        "discovery_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "run_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("station_code", sa.String(length=2), nullable=False),
        sa.Column("trains_discovered", sa.Integer(), nullable=True),
        sa.Column("new_trains", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_details", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_discovery_time", "discovery_runs", ["station_code", "run_at"], unique=False
    )
    op.create_table(
        "train_journeys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("train_id", sa.String(length=10), nullable=False),
        sa.Column("journey_date", sa.Date(), nullable=False),
        sa.Column("line_code", sa.String(length=2), nullable=False),
        sa.Column("line_name", sa.String(length=100), nullable=True),
        sa.Column("line_color", sa.String(length=7), nullable=True),
        sa.Column("destination", sa.String(length=100), nullable=False),
        sa.Column("origin_station_code", sa.String(length=2), nullable=False),
        sa.Column("terminal_station_code", sa.String(length=2), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("update_count", sa.Integer(), nullable=False),
        sa.Column("scheduled_departure", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_arrival", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_departure", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_arrival", sa.DateTime(timezone=True), nullable=True),
        sa.Column("has_complete_journey", sa.Boolean(), nullable=False),
        sa.Column("stops_count", sa.Integer(), nullable=True),
        sa.Column("is_cancelled", sa.Boolean(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("train_id", "journey_date", name="unique_train_journey"),
    )
    op.create_index(
        "idx_journey_date", "train_journeys", ["journey_date"], unique=False
    )
    op.create_index(
        "idx_last_updated", "train_journeys", ["last_updated_at"], unique=False
    )
    op.create_index("idx_train_id", "train_journeys", ["train_id"], unique=False)
    op.create_table(
        "journey_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("journey_id", sa.Integer(), nullable=False),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("raw_stop_list_data", sa.JSON(), nullable=False),
        sa.Column("train_status", sa.String(length=50), nullable=True),
        sa.Column("delay_minutes", sa.Integer(), nullable=True),
        sa.Column("completed_stops", sa.Integer(), nullable=True),
        sa.Column("total_stops", sa.Integer(), nullable=True),
        sa.Column("track_assignments", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["journey_id"],
            ["train_journeys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_captured_at", "journey_snapshots", ["captured_at"], unique=False
    )
    op.create_index(
        "idx_journey_time",
        "journey_snapshots",
        ["journey_id", "captured_at"],
        unique=False,
    )
    op.create_table(
        "journey_stops",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("journey_id", sa.Integer(), nullable=False),
        sa.Column("station_code", sa.String(length=2), nullable=False),
        sa.Column("station_name", sa.String(length=100), nullable=False),
        sa.Column("stop_sequence", sa.Integer(), nullable=False),
        sa.Column("scheduled_arrival", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scheduled_departure", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_arrival", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_departure", sa.DateTime(timezone=True), nullable=True),
        sa.Column("departed", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("status_details", sa.JSON(), nullable=True),
        sa.Column("track", sa.String(length=5), nullable=True),
        sa.Column("track_assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pickup_only", sa.Boolean(), nullable=False),
        sa.Column("dropoff_only", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["journey_id"],
            ["train_journeys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("journey_id", "station_code", name="unique_journey_stop"),
    )
    op.create_index(
        "idx_journey_sequence",
        "journey_stops",
        ["journey_id", "stop_sequence"],
        unique=False,
    )
    op.create_index(
        "idx_station_times",
        "journey_stops",
        ["station_code", "scheduled_departure"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_station_times", table_name="journey_stops")
    op.drop_index("idx_journey_sequence", table_name="journey_stops")
    op.drop_table("journey_stops")
    op.drop_index("idx_journey_time", table_name="journey_snapshots")
    op.drop_index("idx_captured_at", table_name="journey_snapshots")
    op.drop_table("journey_snapshots")
    op.drop_index("idx_train_id", table_name="train_journeys")
    op.drop_index("idx_last_updated", table_name="train_journeys")
    op.drop_index("idx_journey_date", table_name="train_journeys")
    op.drop_table("train_journeys")
    op.drop_index("idx_discovery_time", table_name="discovery_runs")
    op.drop_table("discovery_runs")
    op.drop_index("idx_api_calls", table_name="api_calls")
    op.drop_table("api_calls")
    # ### end Alembic commands ###
