"""make_stop_sequence_nullable

Revision ID: ae677490d55c
Revises: 35705502e85c
Create Date: 2025-09-01 10:57:19.127065

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ae677490d55c"
down_revision = "35705502e85c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "journey_stops", "stop_sequence", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "train_journeys",
        "observation_type",
        existing_type=sa.VARCHAR(length=10),
        comment=None,
        existing_comment="SCHEDULED for schedule API data, OBSERVED for real-time data",
        existing_nullable=False,
        existing_server_default=sa.text("'OBSERVED'::character varying"),
    )
    op.drop_index(op.f("idx_train_journey_observation"), table_name="train_journeys")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_train_journey_observation"),
        "train_journeys",
        ["journey_date", "observation_type"],
        unique=False,
    )
    op.alter_column(
        "train_journeys",
        "observation_type",
        existing_type=sa.VARCHAR(length=10),
        comment="SCHEDULED for schedule API data, OBSERVED for real-time data",
        existing_nullable=False,
        existing_server_default=sa.text("'OBSERVED'::character varying"),
    )
    op.alter_column(
        "journey_stops", "stop_sequence", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
