"""change_biginteger_to_integer

Revision ID: 4225afa0ef51
Revises: remove_api_calls
Create Date: 2025-07-04 20:52:22.554948

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4225afa0ef51"
down_revision = "remove_api_calls"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN for type changes
    # For production (PostgreSQL), these would work fine
    # For development (SQLite), you need to recreate the database

    # Get the bind to check database type
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        # For SQLite, we can't alter column types
        # The simplest solution is to recreate the database
        # or use batch operations (more complex)
        pass
    else:
        # For PostgreSQL and other databases that support ALTER COLUMN
        op.alter_column(
            "discovery_runs",
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.Integer(),
            existing_nullable=False,
        )
        op.alter_column(
            "journey_snapshots",
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.Integer(),
            existing_nullable=False,
        )
        op.alter_column(
            "journey_snapshots",
            "journey_id",
            existing_type=sa.BIGINT(),
            type_=sa.Integer(),
            existing_nullable=False,
        )
        op.alter_column(
            "journey_stops",
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.Integer(),
            existing_nullable=False,
        )
        op.alter_column(
            "journey_stops",
            "journey_id",
            existing_type=sa.BIGINT(),
            type_=sa.Integer(),
            existing_nullable=False,
        )
        op.alter_column(
            "train_journeys",
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.Integer(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        # For SQLite, we can't alter column types
        pass
    else:
        # For PostgreSQL and other databases
        op.alter_column(
            "train_journeys",
            "id",
            existing_type=sa.Integer(),
            type_=sa.BIGINT(),
            existing_nullable=False,
        )
        op.alter_column(
            "journey_stops",
            "journey_id",
            existing_type=sa.Integer(),
            type_=sa.BIGINT(),
            existing_nullable=False,
        )
        op.alter_column(
            "journey_stops",
            "id",
            existing_type=sa.Integer(),
            type_=sa.BIGINT(),
            existing_nullable=False,
        )
        op.alter_column(
            "journey_snapshots",
            "journey_id",
            existing_type=sa.Integer(),
            type_=sa.BIGINT(),
            existing_nullable=False,
        )
        op.alter_column(
            "journey_snapshots",
            "id",
            existing_type=sa.Integer(),
            type_=sa.BIGINT(),
            existing_nullable=False,
        )
        op.alter_column(
            "discovery_runs",
            "id",
            existing_type=sa.Integer(),
            type_=sa.BIGINT(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
