import Foundation

struct Stations {
    static let all: [String] = [
        // NJ Transit stations (major ones)
        "New York Penn Station", "Newark Penn Station", "Secaucus Upper Lvl", "Woodbridge",
        "Metropark", "New Brunswick", "Princeton Junction", "Trenton", "Hamilton",
        "Morristown", "Madison", "Summit", "Millburn", "Short Hills", "Newark Airport",
        "Elizabeth", "Linden", "Rahway", "Metuchen", "Edison", "Iselin", "Perth Amboy",
        "South Amboy", "Aberdeen-Matawan", "Hazlet", "Red Bank", "Little Silver", "Monmouth Park",
        "Long Branch", "Asbury Park", "Bradley Beach", "Belmar", "Spring Lake", "Manasquan",
        "Point Pleasant Beach", "Bay Head", "Montclair State University", "Montclair Heights",
        "Upper Montclair", "Mountain Avenue", "Orange", "East Orange", "Brick Church",
        "Newark Broad Street", "Bloomfield", "Watsessing", "Walnut Street", "Glen Ridge",
        "Ridgewood", "Ho-Ho-Kus", "Waldwick", "Allendale", "Ramsey Route 17", "Ramsey Main Street",
        "Mahwah", "Suffern", "Sloatsburg", "Tuxedo", "Harriman", "Goshen", "Campbell Hall",
        "Salisbury Mills-Cornwall", "New Hampton", "Middletown NJ", "Otisville", "Port Jervis",
        "Denville", "Mount Tabor", "Parsippany", "Boonton", "Mountain Lakes", "Convent Station",
        "Chatham", "New Providence", "Murray Hill", "Berkeley Heights",
        "Gillette", "Stirling", "Millington", "Lyons", "Basking Ridge", "Bernardsville",
        "Far Hills", "Peapack", "Gladstone", "Annandale", "Lebanon", "White House",
        "North Branch", "Raritan", "Somerville", "Bound Brook", "Dunellen", "Plainfield",
        "Netherwood", "Fanwood", "Westfield", "Garwood", "Cranford", "Roselle Park",
        "Union",
        
        // Amtrak stations (Northeast Corridor and beyond)
        "Boston South", "Boston Back Bay", "Providence", "New Haven", "Bridgeport",
        "Stamford", "New Rochelle", "Yonkers", "Croton-Harmon", "Poughkeepsie", "Rhinecliff",
        "Hudson", "Albany-Rensselaer", "Schenectady", "Amsterdam", "Utica", "Rome", "Syracuse",
        "Rochester", "Buffalo-Depew", "Buffalo Exchange Street", "Niagara Falls",
        "Philadelphia",
        "Wilmington", "Aberdeen", "BWI Airport", "Baltimore Penn Station", "New Carrollton",
        "Washington Union", "Alexandria", "Fredericksburg", "Richmond Staples Mill",
        "Richmond Main Street", "Petersburg", "Rocky Mount", "Wilson", "Selma-Smithfield",
        "Raleigh", "Cary", "Southern Pines", "Hamlet", "Fayetteville", "Dillon", "Florence",
        "Kingstree", "Charleston", "Columbia", "Camden", "Denmark", "Savannah", "Jesup",
        "Jacksonville", "Palatka", "DeLand", "Winter Park", "Orlando", "Kissimmee",
        "Lakeland", "Tampa", "Sebring", "Okeechobee", "West Palm Beach", "Delray Beach",
        "Deerfield Beach", "Fort Lauderdale", "Hollywood", "Hallandale Beach", "Aventura",
        "Miami", "Hialeah Market", "Miami Airport", "Toronto Union", "Pittsburgh", "New Orleans", "Norfolk", "Roanoke"
    ].sorted()
    
    // Station name to code mapping
    static let stationCodes: [String: String] = [
        // NJ Transit stations
        "New York Penn Station": "NY",
        "Newark Penn Station": "NP",
        "Secaucus Upper Lvl": "SE",
        "Woodbridge": "WDB",
        "Metropark": "MP",
        "New Brunswick": "NB",
        "Princeton Junction": "PJ",
        "Trenton": "TR",
        "Trenton Transit Center": "TR",
        "Hamilton": "HA",
        "Morristown": "MOR",
        "Madison": "MAD",
        "Summit": "SUM",
        "Millburn": "MIL",
        "Short Hills": "SHI",
        "Newark Airport": "EWR",
        "Elizabeth": "ELZ",
        "Linden": "LI",
        "Rahway": "RAH",
        "Metuchen": "MET",
        "Edison": "EDI",
        "Iselin": "ISE",
        "Perth Amboy": "PAM",
        "South Amboy": "SAM",
        "Aberdeen-Matawan": "ABM",
        "Hazlet": "HAZ",
        "Red Bank": "RBK",
        "Little Silver": "LIS",
        "Monmouth Park": "MPK",
        "Long Branch": "LBR",
        "Asbury Park": "ASB",
        "Bradley Beach": "BRB",
        "Belmar": "BEL",
        "Spring Lake": "SPL",
        "Manasquan": "MAN",
        "Point Pleasant Beach": "PPB",
        "Bay Head": "BAY",
        "Montclair State University": "MSU",
        "Montclair Heights": "MCH",
        "Upper Montclair": "UMC",
        "Mountain Avenue": "MVA",
        "Orange": "ORA",
        "East Orange": "EOR",
        "Brick Church": "BRC",
        "Newark Broad Street": "NBS",
        "Bloomfield": "BLO",
        "Watsessing": "WAT",
        "Walnut Street": "WNS",
        "Glen Ridge": "GLR",
        "Ridgewood": "RID",
        "Ho-Ho-Kus": "HHK",
        "Waldwick": "WAL",
        "Allendale": "ALL",
        "Ramsey Route 17": "RR17",
        "Ramsey Main Street": "RMS",
        "Mahwah": "MAH",
        "Suffern": "SUF",
        "Sloatsburg": "SLO",
        "Tuxedo": "TUX",
        "Harriman": "HAR",
        "Goshen": "GOS",
        "Campbell Hall": "CAM",
        "Salisbury Mills-Cornwall": "SMC",
        "New Hampton": "NHA",
        "Middletown NJ": "MTN",
        "Otisville": "OTI",
        "Port Jervis": "PJE",
        "Denville": "DEN",
        "Mount Tabor": "MTA",
        "Parsippany": "PAR",
        "Boonton": "BOO",
        "Mountain Lakes": "MLA",
        "Convent Station": "CON",
        "Chatham": "CHA",
        "New Providence": "NPR",
        "Murray Hill": "MUR",
        "Berkeley Heights": "BER",
        "Gillette": "GIL",
        "Stirling": "STI",
        "Millington": "MIL2",
        "Lyons": "LYO",
        "Basking Ridge": "BAS",
        "Bernardsville": "BER2",
        "Far Hills": "FAR",
        "Peapack": "PEA",
        "Gladstone": "GLA",
        "Annandale": "ANN",
        "Lebanon": "LEB",
        "White House": "WHI",
        "North Branch": "NBR",
        "Raritan": "RAR",
        "Somerville": "SOM",
        "Bound Brook": "BBK",
        "Dunellen": "DUN",
        "Plainfield": "PLA",
        "Netherwood": "NET",
        "Fanwood": "FAN",
        "Westfield": "WES",
        "Garwood": "GAR",
        "Cranford": "CRA",
        "Roselle Park": "ROP",
        "Union": "UNI",
        
        // Amtrak stations
        "Boston South": "BOS",
        "Boston Back Bay": "BBY",
        "Providence": "PVD",
        "New Haven": "NHV",
        "Bridgeport": "BRP",
        "Stamford": "STM",
        "New Rochelle": "NRO",
        "Yonkers": "YNY",
        "Croton-Harmon": "CRT",
        "Poughkeepsie": "POU",
        "Rhinecliff": "RHI",
        "Hudson": "HUD",
        "Albany-Rensselaer": "ALB",
        "Schenectady": "SCH",
        "Amsterdam": "AMS",
        "Utica": "UTS",
        "Rome": "ROM",
        "Syracuse": "SYR",
        "Rochester": "ROC",
        "Buffalo-Depew": "BUF",
        "Buffalo Exchange Street": "BFX",
        "Niagara Falls": "NFL",
        "Philadelphia": "PHL",
        "Wilmington": "WIL",
        "Aberdeen": "ABE",
        "BWI Airport": "BWI",
        "Baltimore Penn Station": "BAL",
        "New Carrollton": "NCR",
        "Washington Union": "WAS",
        "Alexandria": "AXA",
        "Fredericksburg": "FRB",
        "Richmond Staples Mill": "RSM",
        "Richmond Main Street": "RVM",
        "Petersburg": "PTB",
        "Rocky Mount": "RMT",
        "Wilson": "WIL2",
        "Selma-Smithfield": "SSM",
        "Raleigh": "RAL",
        "Cary": "CAR",
        "Southern Pines": "SPN",
        "Hamlet": "HAM2",
        "Fayetteville": "FAY",
        "Dillon": "DIL",
        "Florence": "FLO",
        "Kingstree": "KTR",
        "Charleston": "CHS",
        "Columbia": "COL",
        "Camden": "CAM2",
        "Denmark": "DEN2",
        "Savannah": "SAV",
        "Jesup": "JES",
        "Jacksonville": "JAX",
        "Palatka": "PAL",
        "DeLand": "DEL",
        "Winter Park": "WPK",
        "Orlando": "ORL",
        "Kissimmee": "KIS",
        "Lakeland": "LAK",
        "Tampa": "TPA",
        "Sebring": "SEB",
        "Okeechobee": "OKE",
        "West Palm Beach": "WPB",
        "Delray Beach": "DRB",
        "Deerfield Beach": "DFB",
        "Fort Lauderdale": "FTL",
        "Hollywood": "HOL",
        "Hallandale Beach": "HLB",
        "Aventura": "AVE",
        "Miami": "MIA",
        "Hialeah Market": "HIA",
        "Miami Airport": "MIP",
        "Toronto Union": "TOR",
        "Pittsburgh": "PIT",
        "New Orleans": "NOL",
        "Norfolk": "NFK",
        "Roanoke": "ROA"
    ]
    
    // Supported departure stations
    static let departureStations: [(name: String, code: String)] = [
        ("New York Penn Station", "NY"),
        ("Newark Penn Station", "NP"),
        ("Metropark", "MP"),
        ("Princeton Junction", "PJ"),
        ("Trenton", "TR")
    ]
    
    static func search(_ query: String) -> [String] {
        guard !query.isEmpty else { return [] }
        let lowercased = query.lowercased()
        return all.filter { $0.lowercased().contains(lowercased) }
            .prefix(8)
            .map { $0 }
    }
    
    static func getStationCode(_ stationName: String) -> String? {
        return stationCodes[stationName]
    }
}
