"""SEPTA Regional Rail station configuration.

Auto-generated by ``scripts/generate_septa_data.py`` from the SEPTA GTFS static
feed (``google_rail.zip``). Do not edit by hand — re-run the generator to
refresh. Internal station codes are the GTFS stop_id prefixed with ``SEPR`` to
stay unique across every TrackRat provider.
"""

# GTFS-RT feeds (public, no authentication). Regional Rail's TripUpdates feed is
# delay-based: each stop_time_update carries a `delay` (seconds) keyed by
# stop_sequence, not an absolute time — the collector joins the static schedule.
SEPTA_RR_GTFS_RT_FEED_URL = (
    "https://www3.septa.org/gtfsrt/septarail-pa-us/Trip/rtTripUpdates.pb"
)
SEPTA_RR_POSITIONS_FEED_URL = (
    "https://www3.septa.org/gtfsrt/septarail-pa-us/Vehicle/rtVehiclePosition.pb"
)
SEPTA_RR_ALERTS_FEED_URL = (
    "https://www3.septa.org/gtfsrt/septarail-pa-us/Service/rtServiceAlerts.pb"
)
SEPTA_RR_GTFS_FEED_URL = "https://www3.septa.org/developer/google_rail.zip"


# Internal code -> display name
SEPTA_RR_STATION_NAMES: dict[str, str] = {
    "SEPR90314": "49th St",
    "SEPR90539": "9th St Lansdale",
    "SEPR90404": "Airport Terminal A",
    "SEPR90403": "Airport Terminal B",
    "SEPR90402": "Airport Terminals C & D",
    "SEPR90401": "Airport Terminals E & F",
    "SEPR90218": "Allegheny",
    "SEPR90526": "Ambler",
    "SEPR90313": "Angora",
    "SEPR90518": "Ardmore",
    "SEPR90412": "Ardsley",
    "SEPR90002": "Bala",
    "SEPR90508": "Berwyn",
    "SEPR90318": "Bethayres",
    "SEPR90710": "Bridesburg",
    "SEPR90703": "Bristol",
    "SEPR90516": "Bryn Mawr",
    "SEPR90805": "Carpenter",
    "SEPR90535": "Chalfont",
    "SEPR90808": "Chelten Av",
    "SEPR90813": "Cheltenham",
    "SEPR90207": "Chester Transit Center",
    "SEPR90720": "Chestnut Hill East",
    "SEPR90801": "Chestnut Hill West",
    "SEPR90202": "Churchman's Crossing",
    "SEPR90204": "Claymont Transit Center",
    "SEPR90309": "Clifton-Aldan",
    "SEPR90533": "Colmar",
    "SEPR90225": "Conshohocken",
    "SEPR90706": "Cornwells Heights",
    "SEPR90414": "Crestmont",
    "SEPR90704": "Croydon",
    "SEPR90209": "Crum Lynne",
    "SEPR90216": "Curtis Park",
    "SEPR90001": "Cynwyd",
    "SEPR90217": "Darby",
    "SEPR90507": "Daylesford",
    "SEPR90537": "Delaware Valley University",
    "SEPR90509": "Devon",
    "SEPR90502": "Downingtown",
    "SEPR90538": "Doylestown",
    "SEPR90219": "East Falls",
    "SEPR90405": "Eastwick",
    "SEPR90705": "Eddington",
    "SEPR90208": "Eddystone",
    "SEPR90409": "Elkins Park",
    "SEPR90301": "Elwyn",
    "SEPR90504": "Exton",
    "SEPR90407": "Fern Rock Transit Center",
    "SEPR90312": "Fernwood-Yeadon",
    "SEPR90214": "Folcroft",
    "SEPR90320": "Forest Hills",
    "SEPR90525": "Fort Washington",
    "SEPR90532": "Fortuna",
    "SEPR90815": "Fox Chase",
    "SEPR90713": "Germantown",
    "SEPR90310": "Gladstone",
    "SEPR90213": "Glenolden",
    "SEPR90411": "Glenside",
    "SEPR90719": "Gravers",
    "SEPR90004": "Gray 30th St Station",
    "SEPR90528": "Gwynedd Valley",
    "SEPR90416": "Hatboro",
    "SEPR90517": "Haverford",
    "SEPR90802": "Highland",
    "SEPR90206": "Highland Av",
    "SEPR90708": "Holmesburg Junction",
    "SEPR90222": "Ivy Ridge",
    "SEPR90006": "Jefferson Station",
    "SEPR90410": "Jenkintown-Wyncote",
    "SEPR90324": "Langhorne",
    "SEPR90531": "Lansdale",
    "SEPR90311": "Lansdowne",
    "SEPR90812": "Lawndale",
    "SEPR90702": "Levittown",
    "SEPR90534": "Link Belt",
    "SEPR90227": "Main St",
    "SEPR90505": "Malvern",
    "SEPR90221": "Manayunk",
    "SEPR90205": "Marcus Hook",
    "SEPR90317": "Meadowbrook",
    "SEPR90302": "Media",
    "SEPR90408": "Melrose Park",
    "SEPR90521": "Merion",
    "SEPR90223": "Miquon",
    "SEPR90306": "Morton",
    "SEPR90717": "Mount Airy",
    "SEPR90303": "Moylan-Rose Valley",
    "SEPR90520": "Narberth",
    "SEPR90323": "Neshaminy Falls",
    "SEPR90536": "New Britain",
    "SEPR90201": "Newark DE",
    "SEPR90315": "Noble",
    "SEPR90228": "Norristown Elm Street",
    "SEPR90226": "Norristown Transit Center",
    "SEPR90008": "North Broad",
    "SEPR90523": "North Hills",
    "SEPR90711": "North Philadelphia Amtrak",
    "SEPR90810": "North Philadelphia Septa",
    "SEPR90529": "North Wales",
    "SEPR90212": "Norwood",
    "SEPR90811": "Olney",
    "SEPR90524": "Oreland",
    "SEPR90522": "Overbrook",
    "SEPR90506": "Paoli",
    "SEPR90527": "Penllyn",
    "SEPR90406": "Penn Medicine Station",
    "SEPR90530": "Pennbrook",
    "SEPR90319": "Philmont",
    "SEPR90308": "Primos",
    "SEPR90211": "Prospect Park",
    "SEPR90809": "Queen Ln",
    "SEPR90513": "Radnor",
    "SEPR90804": "Richard Allen Ln",
    "SEPR90210": "Ridley Park",
    "SEPR90515": "Rosemont",
    "SEPR90413": "Roslyn",
    "SEPR90316": "Rydal",
    "SEPR90814": "Ryers",
    "SEPR90307": "Secane",
    "SEPR90716": "Sedgwick",
    "SEPR90215": "Sharon Hill",
    "SEPR90321": "Somerton",
    "SEPR90224": "Spring Mill",
    "SEPR90512": "St. Davids",
    "SEPR90803": "St. Martins",
    "SEPR90715": "Stenton",
    "SEPR90510": "Strafford",
    "SEPR90005": "Suburban Station",
    "SEPR90305": "Swarthmore",
    "SEPR90709": "Tacony",
    "SEPR90007": "Temple University",
    "SEPR90501": "Thorndale",
    "SEPR90707": "Torresdale",
    "SEPR90701": "Trenton Transit Center",
    "SEPR90322": "Trevose",
    "SEPR90807": "Tulpehocken",
    "SEPR90806": "Upsal",
    "SEPR90514": "Villanova",
    "SEPR90304": "Wallingford",
    "SEPR90417": "Warminster",
    "SEPR90714": "Washington Ln",
    "SEPR90300": "Wawa",
    "SEPR90511": "Wayne",
    "SEPR90009": "Wayne Junction",
    "SEPR90327": "West Trenton",
    "SEPR90503": "Whitford",
    "SEPR90415": "Willow Grove",
    "SEPR90203": "Wilmington",
    "SEPR90220": "Wissahickon",
    "SEPR90712": "Wister",
    "SEPR90325": "Woodbourne",
    "SEPR90718": "Wyndmoor",
    "SEPR90003": "Wynnefield Av",
    "SEPR90519": "Wynnewood",
    "SEPR90326": "Yardley",
}


# GTFS stop_id -> internal code (used by the GTFS static loader; the RT feed
# carries no stop_id, so times are joined to static by (trip_id, stop_sequence)).
SEPTA_RR_GTFS_STOP_TO_INTERNAL_MAP: dict[str, str] = {
    "90314": "SEPR90314",
    "90539": "SEPR90539",
    "90404": "SEPR90404",
    "90403": "SEPR90403",
    "90402": "SEPR90402",
    "90401": "SEPR90401",
    "90218": "SEPR90218",
    "90526": "SEPR90526",
    "90313": "SEPR90313",
    "90518": "SEPR90518",
    "90412": "SEPR90412",
    "90002": "SEPR90002",
    "90508": "SEPR90508",
    "90318": "SEPR90318",
    "90710": "SEPR90710",
    "90703": "SEPR90703",
    "90516": "SEPR90516",
    "90805": "SEPR90805",
    "90535": "SEPR90535",
    "90808": "SEPR90808",
    "90813": "SEPR90813",
    "90207": "SEPR90207",
    "90720": "SEPR90720",
    "90801": "SEPR90801",
    "90202": "SEPR90202",
    "90204": "SEPR90204",
    "90309": "SEPR90309",
    "90533": "SEPR90533",
    "90225": "SEPR90225",
    "90706": "SEPR90706",
    "90414": "SEPR90414",
    "90704": "SEPR90704",
    "90209": "SEPR90209",
    "90216": "SEPR90216",
    "90001": "SEPR90001",
    "90217": "SEPR90217",
    "90507": "SEPR90507",
    "90537": "SEPR90537",
    "90509": "SEPR90509",
    "90502": "SEPR90502",
    "90538": "SEPR90538",
    "90219": "SEPR90219",
    "90405": "SEPR90405",
    "90705": "SEPR90705",
    "90208": "SEPR90208",
    "90409": "SEPR90409",
    "90301": "SEPR90301",
    "90504": "SEPR90504",
    "90407": "SEPR90407",
    "90312": "SEPR90312",
    "90214": "SEPR90214",
    "90320": "SEPR90320",
    "90525": "SEPR90525",
    "90532": "SEPR90532",
    "90815": "SEPR90815",
    "90713": "SEPR90713",
    "90310": "SEPR90310",
    "90213": "SEPR90213",
    "90411": "SEPR90411",
    "90719": "SEPR90719",
    "90004": "SEPR90004",
    "90528": "SEPR90528",
    "90416": "SEPR90416",
    "90517": "SEPR90517",
    "90802": "SEPR90802",
    "90206": "SEPR90206",
    "90708": "SEPR90708",
    "90222": "SEPR90222",
    "90006": "SEPR90006",
    "90410": "SEPR90410",
    "90324": "SEPR90324",
    "90531": "SEPR90531",
    "90311": "SEPR90311",
    "90812": "SEPR90812",
    "90702": "SEPR90702",
    "90534": "SEPR90534",
    "90227": "SEPR90227",
    "90505": "SEPR90505",
    "90221": "SEPR90221",
    "90205": "SEPR90205",
    "90317": "SEPR90317",
    "90302": "SEPR90302",
    "90408": "SEPR90408",
    "90521": "SEPR90521",
    "90223": "SEPR90223",
    "90306": "SEPR90306",
    "90717": "SEPR90717",
    "90303": "SEPR90303",
    "90520": "SEPR90520",
    "90323": "SEPR90323",
    "90536": "SEPR90536",
    "90201": "SEPR90201",
    "90315": "SEPR90315",
    "90228": "SEPR90228",
    "90226": "SEPR90226",
    "90008": "SEPR90008",
    "90523": "SEPR90523",
    "90711": "SEPR90711",
    "90810": "SEPR90810",
    "90529": "SEPR90529",
    "90212": "SEPR90212",
    "90811": "SEPR90811",
    "90524": "SEPR90524",
    "90522": "SEPR90522",
    "90506": "SEPR90506",
    "90527": "SEPR90527",
    "90406": "SEPR90406",
    "90530": "SEPR90530",
    "90319": "SEPR90319",
    "90308": "SEPR90308",
    "90211": "SEPR90211",
    "90809": "SEPR90809",
    "90513": "SEPR90513",
    "90804": "SEPR90804",
    "90210": "SEPR90210",
    "90515": "SEPR90515",
    "90413": "SEPR90413",
    "90316": "SEPR90316",
    "90814": "SEPR90814",
    "90307": "SEPR90307",
    "90716": "SEPR90716",
    "90215": "SEPR90215",
    "90321": "SEPR90321",
    "90224": "SEPR90224",
    "90512": "SEPR90512",
    "90803": "SEPR90803",
    "90715": "SEPR90715",
    "90510": "SEPR90510",
    "90005": "SEPR90005",
    "90305": "SEPR90305",
    "90709": "SEPR90709",
    "90007": "SEPR90007",
    "90501": "SEPR90501",
    "90707": "SEPR90707",
    "90701": "SEPR90701",
    "90322": "SEPR90322",
    "90807": "SEPR90807",
    "90806": "SEPR90806",
    "90514": "SEPR90514",
    "90304": "SEPR90304",
    "90417": "SEPR90417",
    "90714": "SEPR90714",
    "90300": "SEPR90300",
    "90511": "SEPR90511",
    "90009": "SEPR90009",
    "90327": "SEPR90327",
    "90503": "SEPR90503",
    "90415": "SEPR90415",
    "90203": "SEPR90203",
    "90220": "SEPR90220",
    "90712": "SEPR90712",
    "90325": "SEPR90325",
    "90718": "SEPR90718",
    "90003": "SEPR90003",
    "90519": "SEPR90519",
    "90326": "SEPR90326",
}

INTERNAL_TO_SEPTA_RR_GTFS_STOP_MAP: dict[str, str] = {
    v: k for k, v in SEPTA_RR_GTFS_STOP_TO_INTERNAL_MAP.items()
}


# GTFS route_id -> (line_code, display name, color)
SEPTA_RR_ROUTES: dict[str, tuple[str, str, str]] = {
    "AIR": ("SEPTA-AIR", "Airport Line", "#4F758B"),
    "CHE": ("SEPTA-CHE", "Chestnut Hill East Line", "#4F758B"),
    "CHW": ("SEPTA-CHW", "Chestnut Hill West Line", "#4F758B"),
    "CYN": ("SEPTA-CYN", "Cynwyd Line", "#4F758B"),
    "FOX": ("SEPTA-FOX", "Fox Chase Line", "#4F758B"),
    "LAN": ("SEPTA-LAN", "Lansdale/Doylestown Line", "#4F758B"),
    "MED": ("SEPTA-MED", "Media/Wawa Line", "#4F758B"),
    "NOR": ("SEPTA-NOR", "Manayunk/Norristown Line", "#4F758B"),
    "PAO": ("SEPTA-PAO", "Paoli/Thorndale Line", "#4F758B"),
    "TRE": ("SEPTA-TRE", "Trenton Line", "#4F758B"),
    "WAR": ("SEPTA-WAR", "Warminster Line", "#4F758B"),
    "WIL": ("SEPTA-WIL", "Wilmington/Newark Line", "#4F758B"),
    "WTR": ("SEPTA-WTR", "West Trenton Line", "#4F758B"),
}


# Ordered station sequences per line (direction_id=0), from route_stops.txt.
SEPTA_RR_ROUTE_STATIONS: dict[str, tuple[str, ...]] = {
    "AIR": (
        "SEPR90401",
        "SEPR90402",
        "SEPR90403",
        "SEPR90404",
        "SEPR90405",
        "SEPR90406",
        "SEPR90004",
        "SEPR90005",
        "SEPR90006",
        "SEPR90007",
    ),
    "CHE": (
        "SEPR90406",
        "SEPR90004",
        "SEPR90005",
        "SEPR90006",
        "SEPR90007",
        "SEPR90009",
        "SEPR90712",
        "SEPR90713",
        "SEPR90714",
        "SEPR90715",
        "SEPR90716",
        "SEPR90717",
        "SEPR90718",
        "SEPR90719",
        "SEPR90720",
    ),
    "CHW": (
        "SEPR90801",
        "SEPR90802",
        "SEPR90803",
        "SEPR90804",
        "SEPR90805",
        "SEPR90806",
        "SEPR90807",
        "SEPR90808",
        "SEPR90809",
        "SEPR90810",
        "SEPR90004",
        "SEPR90005",
        "SEPR90006",
        "SEPR90007",
    ),
    "CYN": (
        "SEPR90001",
        "SEPR90002",
        "SEPR90003",
        "SEPR90004",
        "SEPR90005",
    ),
    "FOX": (
        "SEPR90406",
        "SEPR90004",
        "SEPR90005",
        "SEPR90006",
        "SEPR90007",
        "SEPR90009",
        "SEPR90811",
        "SEPR90812",
        "SEPR90813",
        "SEPR90814",
        "SEPR90815",
    ),
    "LAN": (
        "SEPR90406",
        "SEPR90004",
        "SEPR90005",
        "SEPR90006",
        "SEPR90007",
        "SEPR90008",
        "SEPR90009",
        "SEPR90407",
        "SEPR90408",
        "SEPR90409",
        "SEPR90410",
        "SEPR90411",
        "SEPR90523",
        "SEPR90524",
        "SEPR90525",
        "SEPR90526",
        "SEPR90527",
        "SEPR90528",
        "SEPR90529",
        "SEPR90530",
        "SEPR90531",
        "SEPR90539",
        "SEPR90532",
        "SEPR90533",
        "SEPR90534",
        "SEPR90535",
        "SEPR90536",
        "SEPR90537",
        "SEPR90538",
    ),
    "MED": (
        "SEPR90300",
        "SEPR90301",
        "SEPR90302",
        "SEPR90303",
        "SEPR90304",
        "SEPR90305",
        "SEPR90306",
        "SEPR90307",
        "SEPR90308",
        "SEPR90309",
        "SEPR90310",
        "SEPR90311",
        "SEPR90312",
        "SEPR90313",
        "SEPR90314",
        "SEPR90406",
        "SEPR90004",
        "SEPR90005",
        "SEPR90006",
        "SEPR90007",
    ),
    "NOR": (
        "SEPR90406",
        "SEPR90004",
        "SEPR90005",
        "SEPR90006",
        "SEPR90007",
        "SEPR90008",
        "SEPR90218",
        "SEPR90219",
        "SEPR90220",
        "SEPR90221",
        "SEPR90222",
        "SEPR90223",
        "SEPR90224",
        "SEPR90225",
        "SEPR90226",
        "SEPR90227",
        "SEPR90228",
    ),
    "PAO": (
        "SEPR90501",
        "SEPR90502",
        "SEPR90503",
        "SEPR90504",
        "SEPR90505",
        "SEPR90506",
        "SEPR90507",
        "SEPR90508",
        "SEPR90509",
        "SEPR90510",
        "SEPR90511",
        "SEPR90512",
        "SEPR90513",
        "SEPR90514",
        "SEPR90515",
        "SEPR90516",
        "SEPR90517",
        "SEPR90518",
        "SEPR90519",
        "SEPR90520",
        "SEPR90521",
        "SEPR90522",
        "SEPR90004",
        "SEPR90005",
        "SEPR90006",
        "SEPR90007",
    ),
    "TRE": (
        "SEPR90701",
        "SEPR90702",
        "SEPR90703",
        "SEPR90704",
        "SEPR90705",
        "SEPR90706",
        "SEPR90707",
        "SEPR90708",
        "SEPR90709",
        "SEPR90710",
        "SEPR90711",
        "SEPR90004",
        "SEPR90005",
        "SEPR90006",
        "SEPR90007",
    ),
    "WAR": (
        "SEPR90406",
        "SEPR90004",
        "SEPR90005",
        "SEPR90006",
        "SEPR90007",
        "SEPR90009",
        "SEPR90407",
        "SEPR90408",
        "SEPR90409",
        "SEPR90410",
        "SEPR90411",
        "SEPR90412",
        "SEPR90413",
        "SEPR90414",
        "SEPR90415",
        "SEPR90416",
        "SEPR90417",
    ),
    "WIL": (
        "SEPR90201",
        "SEPR90202",
        "SEPR90203",
        "SEPR90204",
        "SEPR90205",
        "SEPR90206",
        "SEPR90207",
        "SEPR90208",
        "SEPR90209",
        "SEPR90210",
        "SEPR90211",
        "SEPR90212",
        "SEPR90213",
        "SEPR90214",
        "SEPR90215",
        "SEPR90216",
        "SEPR90217",
        "SEPR90406",
        "SEPR90004",
        "SEPR90005",
        "SEPR90006",
        "SEPR90007",
    ),
    "WTR": (
        "SEPR90406",
        "SEPR90004",
        "SEPR90005",
        "SEPR90006",
        "SEPR90007",
        "SEPR90407",
        "SEPR90408",
        "SEPR90409",
        "SEPR90410",
        "SEPR90315",
        "SEPR90316",
        "SEPR90317",
        "SEPR90318",
        "SEPR90319",
        "SEPR90320",
        "SEPR90321",
        "SEPR90322",
        "SEPR90323",
        "SEPR90324",
        "SEPR90325",
        "SEPR90326",
        "SEPR90327",
    ),
}


# Center City through-stations — coverage-validation hubs.
SEPTA_RR_DISCOVERY_STATIONS = ["SEPR90004", "SEPR90006", "SEPR90005", "SEPR90007"]


# Station coordinates for map visualization
SEPTA_RR_STATION_COORDINATES: dict[str, dict[str, float]] = {
    "SEPR90314": {"lat": 39.94361, "lon": -75.21667},  # 49th St
    "SEPR90539": {"lat": 40.25, "lon": -75.27917},  # 9th St Lansdale
    "SEPR90404": {"lat": 39.87611, "lon": -75.24528},  # Airport Terminal A
    "SEPR90403": {"lat": 39.87722, "lon": -75.24139},  # Airport Terminal B
    "SEPR90402": {"lat": 39.87806, "lon": -75.24},  # Airport Terminals C & D
    "SEPR90401": {"lat": 39.87944, "lon": -75.23972},  # Airport Terminals E & F
    "SEPR90218": {"lat": 40.00361, "lon": -75.16472},  # Allegheny
    "SEPR90526": {"lat": 40.15361, "lon": -75.22472},  # Ambler
    "SEPR90313": {"lat": 39.94472, "lon": -75.23861},  # Angora
    "SEPR90518": {"lat": 40.00828, "lon": -75.2904},  # Ardmore
    "SEPR90412": {"lat": 40.11417, "lon": -75.15305},  # Ardsley
    "SEPR90002": {"lat": 40.00111, "lon": -75.22778},  # Bala
    "SEPR90508": {"lat": 40.04805, "lon": -75.44222},  # Berwyn
    "SEPR90318": {"lat": 40.11666, "lon": -75.06834},  # Bethayres
    "SEPR90710": {"lat": 40.01056, "lon": -75.06973},  # Bridesburg
    "SEPR90703": {"lat": 40.10472, "lon": -74.85472},  # Bristol
    "SEPR90516": {"lat": 40.02195, "lon": -75.31639},  # Bryn Mawr
    "SEPR90805": {"lat": 40.05111, "lon": -75.19139},  # Carpenter
    "SEPR90535": {"lat": 40.28778, "lon": -75.20972},  # Chalfont
    "SEPR90808": {"lat": 40.03, "lon": -75.18083},  # Chelten Av
    "SEPR90813": {"lat": 40.05806, "lon": -75.09278},  # Cheltenham
    "SEPR90207": {"lat": 39.84972, "lon": -75.36},  # Chester Transit Center
    "SEPR90720": {"lat": 40.08111, "lon": -75.20722},  # Chestnut Hill East
    "SEPR90801": {"lat": 40.07639, "lon": -75.20834},  # Chestnut Hill West
    "SEPR90202": {"lat": 39.695, "lon": -75.6725},  # Churchman's Crossing
    "SEPR90204": {"lat": 39.79778, "lon": -75.45222},  # Claymont Transit Center
    "SEPR90309": {"lat": 39.92667, "lon": -75.29028},  # Clifton-Aldan
    "SEPR90533": {"lat": 40.26833, "lon": -75.25445},  # Colmar
    "SEPR90225": {"lat": 40.07328, "lon": -75.310944},  # Conshohocken
    "SEPR90706": {"lat": 40.0709, "lon": -74.95432},  # Cornwells Heights
    "SEPR90414": {"lat": 40.13334, "lon": -75.11861},  # Crestmont
    "SEPR90704": {"lat": 40.09361, "lon": -74.90667},  # Croydon
    "SEPR90209": {"lat": 39.87194, "lon": -75.33111},  # Crum Lynne
    "SEPR90216": {"lat": 39.90805, "lon": -75.265},  # Curtis Park
    "SEPR90001": {"lat": 40.00667, "lon": -75.23167},  # Cynwyd
    "SEPR90217": {"lat": 39.91306, "lon": -75.25445},  # Darby
    "SEPR90507": {"lat": 40.04306, "lon": -75.46056},  # Daylesford
    "SEPR90537": {"lat": 40.29722, "lon": -75.16167},  # Delaware Valley University
    "SEPR90509": {"lat": 40.04722, "lon": -75.42278},  # Devon
    "SEPR90502": {"lat": 40.00219, "lon": -75.71078},  # Downingtown
    "SEPR90538": {"lat": 40.30639, "lon": -75.13028},  # Doylestown
    "SEPR90219": {"lat": 40.01139, "lon": -75.19195},  # East Falls
    "SEPR90405": {"lat": 39.89278, "lon": -75.24389},  # Eastwick
    "SEPR90705": {"lat": 40.08306, "lon": -74.93361},  # Eddington
    "SEPR90208": {"lat": 39.85722, "lon": -75.34222},  # Eddystone
    "SEPR90409": {"lat": 40.07139, "lon": -75.12778},  # Elkins Park
    "SEPR90301": {"lat": 39.9075, "lon": -75.41167},  # Elwyn
    "SEPR90504": {"lat": 40.01929, "lon": -75.62171},  # Exton
    "SEPR90407": {"lat": 40.04055, "lon": -75.13472},  # Fern Rock Transit Center
    "SEPR90312": {"lat": 39.93972, "lon": -75.25584},  # Fernwood-Yeadon
    "SEPR90214": {"lat": 39.90055, "lon": -75.27972},  # Folcroft
    "SEPR90320": {"lat": 40.12778, "lon": -75.02055},  # Forest Hills
    "SEPR90525": {"lat": 40.13583, "lon": -75.21222},  # Fort Washington
    "SEPR90532": {"lat": 40.25945, "lon": -75.26611},  # Fortuna
    "SEPR90815": {"lat": 40.07639, "lon": -75.08334},  # Fox Chase
    "SEPR90713": {"lat": 40.0375, "lon": -75.17167},  # Germantown
    "SEPR90310": {"lat": 39.93278, "lon": -75.28222},  # Gladstone
    "SEPR90213": {"lat": 39.89639, "lon": -75.29},  # Glenolden
    "SEPR90411": {"lat": 40.10139, "lon": -75.15361},  # Glenside
    "SEPR90719": {"lat": 40.0775, "lon": -75.20167},  # Gravers
    "SEPR90004": {"lat": 39.95667, "lon": -75.18166},  # Gray 30th St Station
    "SEPR90528": {"lat": 40.18472, "lon": -75.25694},  # Gwynedd Valley
    "SEPR90416": {"lat": 40.17611, "lon": -75.1025},  # Hatboro
    "SEPR90517": {"lat": 40.01389, "lon": -75.29972},  # Haverford
    "SEPR90802": {"lat": 40.07056, "lon": -75.21111},  # Highland
    "SEPR90206": {"lat": 39.83361, "lon": -75.39333},  # Highland Av
    "SEPR90708": {"lat": 40.03278, "lon": -75.02361},  # Holmesburg Junction
    "SEPR90222": {"lat": 40.03417, "lon": -75.23556},  # Ivy Ridge
    "SEPR90006": {"lat": 39.9525, "lon": -75.15806},  # Jefferson Station
    "SEPR90410": {"lat": 40.09278, "lon": -75.1375},  # Jenkintown-Wyncote
    "SEPR90324": {"lat": 40.16083, "lon": -74.9125},  # Langhorne
    "SEPR90531": {"lat": 40.24278, "lon": -75.285},  # Lansdale
    "SEPR90311": {"lat": 39.9375, "lon": -75.27084},  # Lansdowne
    "SEPR90812": {"lat": 40.05139, "lon": -75.10306},  # Lawndale
    "SEPR90702": {"lat": 40.14028, "lon": -74.81695},  # Levittown
    "SEPR90534": {"lat": 40.27389, "lon": -75.24667},  # Link Belt
    "SEPR90227": {"lat": 40.11722, "lon": -75.34861},  # Main St
    "SEPR90505": {"lat": 40.03639, "lon": -75.51556},  # Malvern
    "SEPR90221": {"lat": 40.02694, "lon": -75.225},  # Manayunk
    "SEPR90205": {"lat": 39.82167, "lon": -75.41944},  # Marcus Hook
    "SEPR90317": {"lat": 40.11139, "lon": -75.0925},  # Meadowbrook
    "SEPR90302": {"lat": 39.91444, "lon": -75.395},  # Media
    "SEPR90408": {"lat": 40.05944, "lon": -75.12917},  # Melrose Park
    "SEPR90521": {"lat": 39.99861, "lon": -75.25139},  # Merion
    "SEPR90223": {"lat": 40.05861, "lon": -75.26639},  # Miquon
    "SEPR90306": {"lat": 39.90778, "lon": -75.32889},  # Morton
    "SEPR90717": {"lat": 40.06528, "lon": -75.19083},  # Mount Airy
    "SEPR90303": {"lat": 39.90611, "lon": -75.38861},  # Moylan-Rose Valley
    "SEPR90520": {"lat": 40.00472, "lon": -75.26139},  # Narberth
    "SEPR90323": {"lat": 40.14695, "lon": -74.96167},  # Neshaminy Falls
    "SEPR90536": {"lat": 40.2975, "lon": -75.17973},  # New Britain
    "SEPR90201": {"lat": 39.66969, "lon": -75.75351},  # Newark DE
    "SEPR90315": {"lat": 40.10444, "lon": -75.12417},  # Noble
    "SEPR90228": {"lat": 40.12083, "lon": -75.345},  # Norristown Elm Street
    "SEPR90226": {"lat": 40.11278, "lon": -75.34417},  # Norristown Transit Center
    "SEPR90008": {"lat": 39.99222, "lon": -75.15389},  # North Broad
    "SEPR90523": {"lat": 40.11195, "lon": -75.16944},  # North Hills
    "SEPR90711": {"lat": 39.99678, "lon": -75.15511},  # North Philadelphia Amtrak
    "SEPR90810": {"lat": 39.99778, "lon": -75.15639},  # North Philadelphia Septa
    "SEPR90529": {"lat": 40.21417, "lon": -75.27722},  # North Wales
    "SEPR90212": {"lat": 39.89167, "lon": -75.30167},  # Norwood
    "SEPR90811": {"lat": 40.03333, "lon": -75.12278},  # Olney
    "SEPR90524": {"lat": 40.11833, "lon": -75.18389},  # Oreland
    "SEPR90522": {"lat": 39.98944, "lon": -75.24944},  # Overbrook
    "SEPR90506": {"lat": 40.04276, "lon": -75.48376},  # Paoli
    "SEPR90527": {"lat": 40.17, "lon": -75.24416},  # Penllyn
    "SEPR90406": {"lat": 39.94806, "lon": -75.19028},  # Penn Medicine Station
    "SEPR90530": {"lat": 40.23028, "lon": -75.28167},  # Pennbrook
    "SEPR90319": {"lat": 40.12194, "lon": -75.04361},  # Philmont
    "SEPR90308": {"lat": 39.92167, "lon": -75.29833},  # Primos
    "SEPR90211": {"lat": 39.88833, "lon": -75.30889},  # Prospect Park
    "SEPR90809": {"lat": 40.02333, "lon": -75.17805},  # Queen Ln
    "SEPR90513": {"lat": 40.04472, "lon": -75.35889},  # Radnor
    "SEPR90804": {"lat": 40.0575, "lon": -75.19473},  # Richard Allen Ln
    "SEPR90210": {"lat": 39.88055, "lon": -75.32222},  # Ridley Park
    "SEPR90515": {"lat": 40.02778, "lon": -75.32667},  # Rosemont
    "SEPR90413": {"lat": 40.12083, "lon": -75.13416},  # Roslyn
    "SEPR90316": {"lat": 40.1075, "lon": -75.11056},  # Rydal
    "SEPR90814": {"lat": 40.06417, "lon": -75.08639},  # Ryers
    "SEPR90307": {"lat": 39.91583, "lon": -75.30972},  # Secane
    "SEPR90716": {"lat": 40.06278, "lon": -75.18528},  # Sedgwick
    "SEPR90215": {"lat": 39.90445, "lon": -75.27084},  # Sharon Hill
    "SEPR90321": {"lat": 40.13055, "lon": -75.01195},  # Somerton
    "SEPR90224": {"lat": 40.07417, "lon": -75.28611},  # Spring Mill
    "SEPR90512": {"lat": 40.04389, "lon": -75.3725},  # St. Davids
    "SEPR90803": {"lat": 40.06583, "lon": -75.20444},  # St. Martins
    "SEPR90715": {"lat": 40.06055, "lon": -75.17861},  # Stenton
    "SEPR90510": {"lat": 40.04945, "lon": -75.40305},  # Strafford
    "SEPR90005": {"lat": 39.95389, "lon": -75.16778},  # Suburban Station
    "SEPR90305": {"lat": 39.90222, "lon": -75.35083},  # Swarthmore
    "SEPR90709": {"lat": 40.02333, "lon": -75.03889},  # Tacony
    "SEPR90007": {"lat": 39.98139, "lon": -75.14944},  # Temple University
    "SEPR90501": {"lat": 39.99278, "lon": -75.76361},  # Thorndale
    "SEPR90707": {"lat": 40.05444, "lon": -74.98444},  # Torresdale
    "SEPR90701": {"lat": 40.21851, "lon": -74.75393},  # Trenton Transit Center
    "SEPR90322": {"lat": 40.14028, "lon": -74.9825},  # Trevose
    "SEPR90807": {"lat": 40.03528, "lon": -75.18694},  # Tulpehocken
    "SEPR90806": {"lat": 40.0425, "lon": -75.19},  # Upsal
    "SEPR90514": {"lat": 40.03833, "lon": -75.34167},  # Villanova
    "SEPR90304": {"lat": 39.90361, "lon": -75.37194},  # Wallingford
    "SEPR90417": {"lat": 40.19528, "lon": -75.08916},  # Warminster
    "SEPR90714": {"lat": 40.05083, "lon": -75.17139},  # Washington Ln
    "SEPR90300": {"lat": 39.90068, "lon": -75.45856},  # Wawa
    "SEPR90511": {"lat": 40.04583, "lon": -75.38667},  # Wayne
    "SEPR90009": {"lat": 40.02222, "lon": -75.16},  # Wayne Junction
    "SEPR90327": {"lat": 40.25778, "lon": -74.81528},  # West Trenton
    "SEPR90503": {"lat": 40.01472, "lon": -75.63805},  # Whitford
    "SEPR90415": {"lat": 40.14389, "lon": -75.11417},  # Willow Grove
    "SEPR90203": {"lat": 39.73726, "lon": -75.55109},  # Wilmington
    "SEPR90220": {"lat": 40.01667, "lon": -75.21028},  # Wissahickon
    "SEPR90712": {"lat": 40.03611, "lon": -75.16111},  # Wister
    "SEPR90325": {"lat": 40.1925, "lon": -74.88917},  # Woodbourne
    "SEPR90718": {"lat": 40.07333, "lon": -75.19666},  # Wyndmoor
    "SEPR90003": {"lat": 39.99, "lon": -75.22556},  # Wynnefield Av
    "SEPR90519": {"lat": 40.00278, "lon": -75.2725},  # Wynnewood
    "SEPR90326": {"lat": 40.23528, "lon": -74.83056},  # Yardley
}


def get_septa_rr_route_info(gtfs_route_id: str) -> tuple[str, str, str] | None:
    """Get SEPTA Regional Rail route info from a GTFS route_id (e.g. "AIR")."""
    return SEPTA_RR_ROUTES.get(gtfs_route_id)


def map_septa_rr_gtfs_stop(gtfs_stop_id: str) -> str | None:
    """Map a SEPTA Regional Rail GTFS stop_id to our internal station code."""
    return SEPTA_RR_GTFS_STOP_TO_INTERNAL_MAP.get(gtfs_stop_id)
