import Foundation

extension Stations {
    static let all: [String] = [
        // Major Hub Stations
        "New York Penn Station", "Newark Penn Station", "Hoboken",
        "Secaucus Upper Lvl", "Secaucus Lower Lvl", "Secaucus Concourse",
        "Trenton", "Philadelphia",
        
        // Northeast Corridor Line
        "Princeton Junction", "Princeton", "Hamilton",
        "Metropark", "New Brunswick", "Edison", "Metuchen",
        "Rahway", "Linden", "Elizabeth", "North Elizabeth",
        "Newark Airport", "Newark Broad Street",
        
        // North Jersey Coast Line  
        "Woodbridge", "Perth Amboy", "South Amboy", "Aberdeen-Matawan",
        "Hazlet", "Middletown", "Red Bank", "Little Silver",
        "Monmouth Park", "Long Branch", "Elberon", "Allenhurst",
        "Asbury Park", "Bradley Beach", "Belmar", "Spring Lake",
        "Manasquan", "Point Pleasant Beach", "Bay Head",
        
        // Morris & Essex Lines
        "Summit NJ", "Chatham", "Madison", "Convent Station",
        "Morristown", "Morris Plains", "Denville", "Dover",
        "Mount Tabor", "Mount Arlington", "Lake Hopatcong", "Netcong",
        "Mount Olive", "Hackettstown", "Millburn", "Short Hills",
        "South Orange", "Maplewood", "Orange", "East Orange",
        "Brick Church", "Highland Avenue", "Mountain View",
        
        // Gladstone Branch
        "Murray Hill", "New Providence", "Berkeley Heights", "Gillette",
        "Stirling", "Millington", "Lyons", "Basking Ridge",
        "Bernardsville", "Far Hills", "Peapack", "Gladstone",
        
        // Raritan Valley Line
        "Union", "Roselle Park", "Cranford", "Garwood", "Westfield",
        "Fanwood", "Netherwood", "Plainfield", "Dunellen",
        "Bound Brook", "Bridgewater", "Somerville", "Raritan",
        "High Bridge", "Annandale", "Lebanon", "White House",
        "North Branch",
        
        // Main/Bergen County Lines
        "Kingsland", "Lyndhurst", "Delawanna", "Passaic", "Clifton",
        "Paterson", "Hawthorne", "Glen Rock Main Line", "Glen Rock Boro Hall",
        "Ridgewood", "Ho-Ho-Kus", "Waldwick", "Allendale",
        "Ramsey Main St", "Ramsey Route 17", "Mahwah", "Suffern",
        "Fair Lawn-Broadway", "Radburn Fair Lawn", "Garfield", "Plauderville",
        "Rutherford", "Wesmont",
        
        // Montclair-Boonton Line
        "Bloomfield", "Glen Ridge", "Bay Street", "Walnut Street",
        "Montclair Heights", "Montclair State U", "Upper Montclair",
        "Mountain Avenue", "Watchung Avenue", "Watsessing Avenue",
        "Little Falls", "Wayne-Route 23", "Mountain Station",
        "Boonton", "Mountain Lakes", "Lincoln Park", "Towaco",
        "Great Notch",
        
        // Pascack Valley Line
        "Wood Ridge", "Teterboro", "Essex Street", "Anderson Street",
        "New Bridge Landing", "River Edge", "Oradell", "Emerson",
        "Westwood", "Hillsdale", "Woodcliff Lake", "Park Ridge",
        "Montvale", "Pearl River", "Nanuet", "Spring Valley",
        
        // Port Jervis Line
        "Sloatsburg", "Tuxedo", "Harriman", "Salisbury Mills-Cornwall",
        "Campbell Hall", "Otisville", "Port Jervis",
        
        // Atlantic City Line
        "Pennsauken", "Cherry Hill", "Lindenwold NJT", "Atco",
        "Hammonton", "Egg Harbor City", "Absecon", "Atlantic City Rail Terminal",

        // Additional NJ Transit Stations
        "Avenel", "Jersey Avenue",

        // PATH Stations
        "Newark PATH", "Harrison PATH", "Journal Square",
        "Grove Street", "Exchange Place", "Newport",
        "Hoboken PATH", "Christopher Street", "9th Street",
        "14th Street", "23rd Street", "33rd Street",
        "World Trade Center",

        // PATCO Speedline Stations (Philadelphia - South Jersey)
        "Lindenwold", "Ashland PATCO", "Woodcrest", "Haddonfield",
        "Westmont", "Collingswood", "Ferry Avenue", "Broadway PATCO",
        "City Hall PATCO", "Franklin Square", "8th and Market",
        "9-10th and Locust", "12-13th and Locust", "15-16th and Locust",

        // Pennsylvania Stations (Keystone Service)
        "Middletown PA", "Elizabethtown", "Mount Joy", "Parkesburg",
        "Coatesville", "Downingtown", "Exton", "Paoli",

        // LIRR Stations (Long Island Rail Road)
        "Albertson", "Amagansett", "Amityville", "Atlantic Terminal",
        "Auburndale", "Babylon", "Baldwin", "Bay Shore", "Bayside",
        "Bellerose", "Bellmore", "Bellport", "Belmont Park", "Bethpage",
        "Brentwood", "Bridgehampton", "Broadway LIRR", "Carle Place",
        "Cedarhurst", "Central Islip", "Centre Avenue", "Cold Spring Harbor",
        "Copiague", "Country Life Press", "Deer Park", "Douglaston",
        "East Hampton", "East New York", "East Rockaway", "East Williston",
        "Elmont-UBS Arena", "Far Rockaway", "Farmingdale", "Floral Park",
        "Flushing Main Street", "Forest Hills", "Freeport", "Garden City",
        "Gibson", "Glen Cove", "Glen Head", "Glen Street",
        "Great Neck", "Great River", "Greenlawn", "Greenport", "Greenvale",
        "Hampton Bays", "Hempstead Gardens", "Hempstead", "Hewlett", "Hicksville",
        "Hollis", "Hunterspoint Avenue", "Huntington", "Inwood", "Island Park",
        "Islip", "Jamaica", "Kew Gardens", "Kings Park", "Lakeview",
        "Laurelton", "Lawrence", "Lindenhurst", "Little Neck", "Locust Manor",
        "Locust Valley", "Long Beach", "Long Island City", "Lynbrook",
        "Malverne", "Manhasset", "Massapequa Park", "Massapequa",
        "Mastic-Shirley", "Mattituck", "Medford", "Merillon Avenue", "Merrick",
        "Mets-Willets Point", "Mineola", "Montauk", "Murray Hill LIRR",
        "Nassau Boulevard", "New Hyde Park", "Northport", "Nostrand Avenue",
        "Oakdale", "Oceanside", "Oyster Bay", "Patchogue", "Pinelawn",
        "Plandome", "Port Jefferson", "Port Washington", "Queens Village",
        "Riverhead", "Rockville Centre", "Ronkonkoma", "Rosedale", "Roslyn",
        "Sayville", "Sea Cliff", "Seaford", "Smithtown", "Southampton",
        "Southold", "Speonk", "St. Albans", "St. James", "Stewart Manor",
        "Stony Brook", "Syosset", "Valley Stream", "Wantagh", "West Hempstead",
        "Westbury", "Westhampton", "Westwood LIRR", "Woodmere", "Woodside",
        "Wyandanch", "Yaphank",

        // Metro-North Railroad Stations
        // Hudson Line
        "Grand Central Terminal", "Harlem-125th Street", "Yankees-E 153 St",
        "Morris Heights", "University Heights", "Marble Hill",
        "Spuyten Duyvil", "Riverdale", "Ludlow", "Yonkers",
        "Glenwood", "Greystone", "Hastings-on-Hudson", "Dobbs Ferry",
        "Ardsley-on-Hudson", "Irvington", "Tarrytown", "Philipse Manor",
        "Scarborough", "Ossining", "Croton-Harmon", "Cortlandt",
        "Peekskill", "Manitou", "Garrison", "Cold Spring",
        "Breakneck Ridge", "Beacon", "New Hamburg", "Poughkeepsie",
        // Harlem Line
        "Melrose", "Tremont", "Fordham", "Botanical Garden",
        "Williams Bridge", "Woodlawn", "Wakefield", "Mt Vernon West",
        "Fleetwood", "Bronxville", "Tuckahoe", "Crestwood",
        "Scarsdale", "Hartsdale", "White Plains", "North White Plains",
        "Valhalla", "Mt Pleasant", "Hawthorne NY", "Pleasantville",
        "Chappaqua", "Mt Kisco", "Bedford Hills", "Katonah",
        "Goldens Bridge", "Purdys", "Croton Falls", "Brewster",
        "Southeast", "Patterson", "Pawling", "Appalachian Trail",
        "Harlem Valley-Wingdale", "Dover Plains", "Tenmile River", "Wassaic",
        // New Haven Line
        "Mt Vernon East", "Pelham", "New Rochelle", "Larchmont",
        "Mamaroneck", "Harrison", "Rye", "Port Chester",
        "Greenwich", "Cos Cob", "Riverside", "Old Greenwich",
        "Stamford", "Noroton Heights", "Darien", "Rowayton",
        "South Norwalk", "East Norwalk", "Westport",
        "Greens Farms", "Southport", "Fairfield", "Fairfield-Black Rock",
        "Bridgeport", "Stratford", "Milford", "West Haven",
        "New Haven", "New Haven-State St",
        // New Canaan Branch
        "Glenbrook", "Springdale", "Talmadge Hill", "New Canaan",
        // Danbury Branch
        "Merritt 7", "Wilton", "Cannondale", "Branchville",
        "Redding", "Bethel", "Danbury",
        // Waterbury Branch
        "Derby-Shelton", "Ansonia", "Seymour", "Beacon Falls",
        "Naugatuck", "Waterbury",

        // Amtrak Northeast Corridor
        "Boston South", "Boston Back Bay", "Providence", "Kingston", "Westerly",
        "New London", "Old Saybrook",
        "Baltimore Station", "BWI Thurgood Marshall Airport",
        "Washington Union Station", "Wilmington DE",
        
        // Additional Amtrak Stations
        "Hartford", "Meriden", "Wallingford", "Windsor Locks", "Springfield MA",
        "Claremont NH", "Dover NH", "Durham-UNH", "Exeter",
        "New Carrollton", "Aberdeen", "Alexandria", "Charlottesville",
        "Lorton", "Manassas", "Norfolk", "Richmond Main Street", "Richmond Staples Mill Road", "Roanoke",
        "Harrisburg", "Lancaster",
        
        // Southeast Amtrak Stations (Silver Star/Meteor and Carolinian/Piedmont routes)
        "Charlotte", "Raleigh", "Greensboro", "Durham", "Rocky Mount", "Wilson",
        "Cary", "Southern Pines", "High Point", "Salisbury", "Gastonia", "Hamlet",
        "Selma-Smithfield", "Petersburg",
        "Charleston SC", "Spartanburg", "Greenville", "Kingstree", "Florence", "Dillon", "Clemson",
        "Savannah", "Atlanta", "Jesup", "Gainesville GA", "Toccoa",
        "Jacksonville", "Miami", "Orlando", "Tampa", "Fort Lauderdale", "West Palm Beach",
        "Kissimmee", "Lakeland", "Winter Park FL", "DeLand", "Sanford FL", "Hollywood FL",
        "Delray Beach", "Waldo", "Ocala", "Winter Haven", "Palatka", "Thurmond",

        // Nationwide Amtrak Stations
        // Major hubs and junctions
        "Chicago Union Station", "St. Louis", "Milwaukee",
        "Los Angeles Union Station", "Seattle King Street", "Portland Union Station",
        "Emeryville", "Sacramento", "New Orleans", "San Antonio", "Denver Union Station",
        // California / Southwest
        "Santa Barbara", "San Luis Obispo", "San Jose", "Oceanside CA", "Santa Ana",
        "Fullerton", "San Diego Old Town", "Albuquerque", "Flagstaff", "Tucson",
        "El Paso", "Reno", "Truckee",
        // Pacific Northwest
        "Spokane", "Tacoma", "Eugene", "Salem OR", "Salt Lake City",
        "Whitefish", "East Glacier Park", "Havre", "St. Paul-Minneapolis",
        // Texas / South Central
        "Dallas", "Fort Worth", "Houston", "Austin", "Little Rock", "Memphis",
        // Midwest / Great Lakes
        "Kansas City", "Oklahoma City", "Omaha", "Indianapolis", "Cincinnati",
        "Cleveland", "Toledo", "Detroit", "Grand Rapids", "Pittsburgh",
        // Northeast extensions
        "Albany-Rensselaer", "Syracuse", "Rochester", "Buffalo Depew", "Montreal",
        "Portland ME", "Essex Junction", "Burlington VT",
        // Virginia / Southeast
        "Lynchburg", "Newport News", "Williamsburg VA", "Columbia SC", "Birmingham", "Mobile",

        // Additional Amtrak stations (nationwide expansion)
        "Anaheim", "Arcata CA", "Auburn", "Barstow", "Burbank Airport", "Bakersfield",
        "Berkeley", "Burbank Downtown", "Chico", "Claremont CA", "Camarillo", "Colfax",
        "Carpinteria", "Chatsworth", "Davis", "Dublin-Pleasanton", "Dunsmuir", "Elko",
        "Fairfield-Vacaville", "Fremont", "Fresno", "Santa Clara Great America", "Glendale", "Gilroy",
        "Goleta", "Guadalupe", "Grover Beach", "Hayward", "Hanford",
        "Irvine", "Lodi", "Lompoc-Surf", "Las Vegas NV", "Merced", "Moorpark",
        "Marysville", "Martinez", "Seaside-Marina", "Santa Clarita-Newhall", "Northridge", "Oakland Coliseum/Airport",
        "Oakland", "Ontario", "Oxnard", "Pomona", "Paso Robles", "Palm Springs",
        "Petaluma", "Redding CA", "Richmond", "Riverside CA", "Rocklin", "Roseville",
        "Santa Clara", "San Francisco", "Simi Valley", "Stockton ACE", "Stockton San Joaquins", "Santa Monica Pier",
        "San Bernardino", "San Juan Capistrano", "San Clemente Pier", "Salinas", "Solana Beach", "Suisun-Fairfield",
        "Vallejo", "Ventura", "Van Nuys", "Victorville", "Winnemucca", "Willits Calif Western Railroad Depot",
        "Albion", "Ann Arbor", "Bangor", "Battle Creek", "Columbus", "Dearborn",
        "Durand", "Erie", "Flint", "Glenview", "Holland", "Jackson MI",
        "Kalamazoo", "East Lansing", "Lapeer", "General Mitchell Intl. Airport", "Pontiac MI", "Portage",
        "Port Huron", "Royal Oak", "St. Joseph-Benton Harbor", "Sturtevant", "Troy", "Wisconsin Dells",
        "Altoona", "Ardmore PA", "Berlin", "Branford", "Bowie State", "Clinton",
        "Connellsville", "Cumberland", "Cornwells Heights",
        "Edgewood", "Greensburg", "Guilford", "Halethorpe", "Harpers Ferry",
        "Huntingdon", "Johnstown", "Latrobe", "Lewistown", "Madison CT", "Middletown CT",
        "Martinsburg", "Martin Airport", "Mystic", "Newark", "Odenton",
        "North Philadelphia", "Perryville", "Rhinecliff",
        "Rockville", "Tyrone", "West Baltimore", "Windsor", "Westbrook",
        "Ashland KY", "Alliance", "Alderson", "Bloomington-Normal", "Bryan",
        "Carbondale", "Centralia IL", "Champaign-Urbana", "Charleston WV", "Connersville", "Crawfordsville",
        "Carlinville", "Dowagiac", "Du Quoin", "Dwight", "Dyer", "Effingham",
        "Elkhart", "Elyria", "Fulton", "Gilman", "Hinton", "Hammond-Whiting",
        "Homewood", "Huntington WV", "Joliet Gateway Center", "Kannapolis", "Kewanee", "Kankakee",
        "Lafayette IN", "La Grange", "Lincoln IL", "Mattoon", "Maysville", "Mendota",
        "Montgomery", "Newbern-Dyersburg", "New Buffalo", "Niles", "Naperville", "Princeton IL",
        "Peoria", "Plano", "Pontiac IL", "Prince", "Rensselaer", "Rantoul",
        "Sandusky", "Summit IL", "South Bend", "Springfield IL", "South Portsmouth",
        "White Sulphur Springs", "Waterloo", "Arcadia Valley", "Ardmore OK", "Alton", "Alpine",
        "Arkadelphia", "Beaumont", "Brookhaven", "Burlington IA", "Cleburne", "Creston",
        "Dodge City", "Detroit Lakes", "Del Rio", "Devils Lake", "Fargo", "Fort Madison",
        "Fort Morgan", "Galesburg", "Garden City KS", "Grand Forks", "Gainesville TX", "Greenwood",
        "Hastings", "Hazlehurst", "Hermann", "Holdrege", "Hammond", "Hope",
        "Hutchinson", "Independence", "Jackson MS", "Jefferson City", "Killeen", "Kirkwood",
        "La Junta", "La Plata", "Lbo", "Lake Charles", "Lee'S Summit", "Lafayette LA",
        "Lamar", "Lincoln NE", "Lawrence KS", "La Crosse", "Longview", "Macomb",
        "Mccomb", "Mcgregor", "Mccook", "Marshall", "Mineola TX", "Marks",
        "Minot", "Mt. Pleasant", "Malvern", "New Iberia", "Norman", "Osceola",
        "Ottumwa", "Poplar Bluff", "Purcell", "Pauls Valley", "Quincy", "Raton",
        "Red Wing", "Rugby", "St. Cloud", "Schriever", "Sedalia", "Shreveport Sportran Intermodal Terminal",
        "San Marcos", "Sanderson", "Staples", "Stanley", "Taylor", "Tomah",
        "Topeka", "Temple", "Trinidad", "Texarkana", "Washington", "Warrensburg",
        "Wellington", "Wichita", "Winona", "Walnut Ridge", "Williston", "Yazoo City",
        "Amsterdam", "Aldershot", "Buffalo", "Bellows Falls", "Boston North", "Brattleboro",
        "Brunswick", "Canadian Border", "Castleton", "Fort Edward", "Framingham", "Freeport ME",
        "Ticonderoga", "Greenfield", "Grimsby", "Haverhill", "Holyoke", "Hudson",
        "Middlebury", "Montpelier-Berlin", "Niagara Falls NY", "Niagara Falls ON", "Northampton", "Oakville",
        "Old Orchard Beach", "Pittsfield", "Plattsburgh", "Port Henry", "Rome", "Randolph",
        "Rouses Point", "Route 128", "Rutland", "St. Albans VT", "Saco", "Saratoga Springs",
        "St. Catherines", "Schenectady", "St-Lambert", "Toronto", "Utica", "Ferrisburgh",
        "Waterbury-Stowe", "Wells", "Whitehall", "Windsor-Mt. Ascutney", "Woburn", "Worcester Union",
        "White River Junction", "Westport", "Albany", "Bellingham", "Bingen-White Salmon", "Browning",
        "Chemult", "Centralia WA", "Cut Bank", "Edmonds", "Ephrata", "Essex",
        "Everett", "Glasgow", "Granby", "Kelso-Longview", "Klamath Falls", "Libby",
        "Leavenworth", "Malta", "Mount Vernon", "Olympia-Lacey", "Oregon City", "Provo",
        "Pasco", "Shelby", "Sandpoint", "Stanwood", "Tukwila", "Vancouver WA",
        "Vancouver BC", "Wenatchee", "West Glacier", "Wishram", "Wolf Point", "Anniston",
        "Bay St Louis", "Bradenton", "Biloxi Amtrak Sta", "Camden", "Deerfield Beach", "Denmark",
        "Gainesville FL", "Gulfport Amtrak Sta", "Hattiesburg", "Hollywood",
        "Laurel", "Meridian Union", "Okeechobee", "Pascagoula", "Picayune",
        "Sebring", "Slidell", "Sanford Amtrak Auto Train", "St. Petersburg", "Tuscaloosa",
        "Wildwood", "Yemassee", "Burke Centre", "Burlington NC", "Clifton Forge",
        "Culpeper", "Danville", "Fayetteville", "Fredericksburg", "Goldsboro",
        "Havelock", "Kinston", "Morehead City", "Quantico", "Seabrook",
        "Selma", "Staunton", "Swansboro", "Woodbridge VA", "Wilmington NC",
        "Benson", "Deming", "Grand Junction", "Gallup", "Green River", "Glenwood Springs",
        "Helper", "Kingman", "Lordsburg", "Lamy", "Las Vegas NM", "Maricopa",
        "Needles", "Phoenix Sky Harbor Airport", "North Phoenix Metro Center Transit", "Santa Fe", "Winter Park/Fraser", "Winslow",
        "Williams", "Winter Park Ski Resort", "Winter Park", "Yuma",

        // NYC Subway Stations (consolidated — one entry per physical station complex)
        "Van Cortlandt Park-242 St",
        "238 St",
        "231 St",
        "Marble Hill-225 St",
        "215 St",
        "207 St",
        "Dyckman St",
        "191 St",
        "181 St",
        "168 St",
        "157 St",
        "145 St",
        "137 St-City College",
        "125 St",
        "116 St-Columbia University",
        "Cathedral Pkwy (110 St)",
        "103 St (1/A/B/C)",
        "96 St (1/2/3/A/B/C)",
        "86 St (1/2)",
        "79 St (1/2)",
        "72 St (1/2/3)",
        "66 St-Lincoln Center",
        "59 St-Columbus Circle",
        "50 St (1/2/A/C/E)",
        "Times Sq-42 St",
        "34 St-Penn Station",
        "28 St (1/2)",
        "23 St (1/2)",
        "18 St",
        "14 St (1/2/3/F/L/M)",
        "Christopher St-Stonewall",
        "Houston St",
        "Canal St",
        "Franklin St",
        "Chambers St",
        "Rector St (1)",
        "Rector St (N/R/W)",
        "South Ferry",
        "Wakefield-241 St",
        "Nereid Av",
        "233 St",
        "225 St",
        "219 St",
        "Gun Hill Rd",
        "Burke Av",
        "Allerton Av",
        "Pelham Pkwy",
        "Bronx Park East",
        "E 180 St",
        "West Farms Sq-E Tremont Av",
        "174 St",
        "Freeman St",
        "Simpson St",
        "Intervale Av",
        "Prospect Av (2/5)",
        "Jackson Av",
        "3 Av-149 St",
        "149 St-Grand Concourse",
        "135 St (2/3)",
        "116 St (2/3)",
        "110 St-Malcolm X Plaza",
        "Chambers St-WTC",
        "Fulton St (2/3/4/5/A/C/J/Z)",
        "Wall St (2/3)",
        "Wall St (4/5)",
        "Clark St",
        "Borough Hall",
        "Hoyt St",
        "Nevins St",
        "Atlantic Av-Barclays Ctr",
        "Bergen St (2/3/4)",
        "Grand Army Plaza",
        "Eastern Pkwy-Brooklyn Museum",
        "Franklin Av (2/3/4/5/FS)",
        "President St-Medgar Evers College",
        "Sterling St",
        "Winthrop St",
        "Church Av (2/5)",
        "Beverly Rd",
        "Newkirk Av-Little Haiti",
        "Flatbush Av-Brooklyn College",
        "Nostrand Av (2/3/4/5)",
        "Kingston Av",
        "Crown Hts-Utica Av",
        "Sutter Av-Rutland Rd",
        "Saratoga Av",
        "Rockaway Av (2/3/4/5)",
        "Livonia Av",
        "Pennsylvania Av",
        "Van Siclen Av (2/3/4/5)",
        "New Lots Av (2/3/4/5)",
        "Harlem-148 St",
        "Woodlawn (4)",
        "Mosholu Pkwy",
        "Bedford Park Blvd-Lehman College",
        "Kingsbridge Rd (4)",
        "Fordham Rd (4)",
        "183 St",
        "Burnside Av",
        "176 St",
        "Mt Eden Av",
        "170 St (4)",
        "167 St (4)",
        "161 St-Yankee Stadium",
        "138 St-Grand Concourse",
        "Bowling Green",
        "Eastchester-Dyre Av",
        "Baychester Av",
        "Morris Park",
        "Pelham Bay Park",
        "Buhre Av",
        "Middletown Rd",
        "Westchester Sq-E Tremont Av",
        "Zerega Av",
        "Castle Hill Av",
        "Parkchester",
        "St Lawrence Av",
        "Morrison Av-Soundview",
        "Elder Av",
        "Whitlock Av",
        "Hunts Point Av",
        "Longwood Av",
        "E 149 St",
        "E 143 St-St Mary's St",
        "Cypress Av",
        "Brook Av",
        "3 Av-138 St",
        "116 St (4/6)",
        "110 St",
        "103 St (4/6)",
        "96 St (4/6)",
        "86 St (4/5/6)",
        "77 St (4/6)",
        "68 St-Hunter College",
        "Lexington Av/59 St",
        "Lexington Av/53 St",
        "Grand Central-42 St",
        "33 St",
        "28 St (4/6)",
        "23 St-Baruch College",
        "14 St-Union Sq",
        "Astor Pl",
        "Broadway-Lafayette St",
        "Spring St (4/6)",
        "Brooklyn Bridge-City Hall",
        "Flushing-Main St",
        "Mets-Willets Point (7)",
        "111 St (7)",
        "103 St-Corona Plaza",
        "Junction Blvd",
        "90 St-Elmhurst Av",
        "82 St-Jackson Hts",
        "Jackson Hts-Roosevelt Av",
        "69 St",
        "61 St-Woodside",
        "52 St",
        "46 St-Bliss St",
        "40 St-Lowery St",
        "33 St-Rawson St",
        "Queensboro Plaza",
        "Court Sq",
        "Hunters Point Av",
        "Vernon Blvd-Jackson Av",
        "42 St-Bryant Pk",
        "34 St-Hudson Yards",
        "Inwood-207 St",
        "190 St",
        "175 St",
        "163 St-Amsterdam Av",
        "155 St",
        "135 St (A/B/C)",
        "116 St (A/B/C)",
        "86 St (A/B/C)",
        "81 St-Museum of Natural History",
        "72 St (A/B/C)",
        "23 St (A/C/E)",
        "14 St (A/C/E/L)",
        "W 4 St-Wash Sq",
        "Spring St (A/C/E)",
        "High St",
        "Jay St-MetroTech",
        "Hoyt-Schermerhorn Sts",
        "Lafayette Av",
        "Clinton-Washington Avs (A/C)",
        "Franklin Av (A/C/FS)",
        "Nostrand Av (A/C)",
        "Kingston-Throop Avs",
        "Utica Av",
        "Ralph Av",
        "Rockaway Av (A/C)",
        "Broadway Junction",
        "Liberty Av",
        "Van Siclen Av (A/C)",
        "Shepherd Av",
        "Euclid Av",
        "Grant Av",
        "80 St",
        "88 St",
        "Rockaway Blvd",
        "104 St (A)",
        "111 St (A)",
        "Ozone Park-Lefferts Blvd",
        "21 St-Queensbridge",
        "Roosevelt Island",
        "57 St",
        "9 Av",
        "Fort Hamilton Pkwy (D)",
        "50 St (D)",
        "55 St",
        "New Utrecht Av",
        "71 St",
        "79 St (D)",
        "18 Av (D)",
        "20 Av (D)",
        "Bay Pkwy (D/R/W)",
        "25 Av",
        "Bay 50 St",
        "Norwood-205 St",
        "Bedford Park Blvd",
        "Kingsbridge Rd (B/D)",
        "Fordham Rd (B/D)",
        "182-183 Sts",
        "Tremont Av",
        "174-175 Sts",
        "170 St (B/D)",
        "167 St (B/D)",
        "7 Av (B/D/E)",
        "47-50 Sts-Rockefeller Ctr",
        "34 St-Herald Sq",
        "23 St (F/M)",
        "Grand St (B/D)",
        "7 Av (B/Q/F/G)",
        "Prospect Park",
        "Parkside Av",
        "Church Av (B/Q)",
        "Beverley Rd",
        "Cortelyou Rd",
        "Newkirk Plaza",
        "Avenue H",
        "Avenue J",
        "Avenue M",
        "Kings Hwy (B/Q)",
        "Avenue U (Q)",
        "Neck Rd",
        "Sheepshead Bay",
        "Brighton Beach",
        "Ocean Pkwy",
        "W 8 St-NY Aquarium",
        "Coney Island-Stillwell Av",
        "Jamaica-179 St",
        "169 St",
        "Parsons Blvd",
        "Sutphin Blvd",
        "Briarwood",
        "Kew Gardens-Union Tpke",
        "75 Av",
        "5 Av/53 St",
        "2 Av",
        "Delancey St-Essex St",
        "East Broadway",
        "York St",
        "Bergen St (F/G)",
        "Carroll St",
        "Smith-9 Sts",
        "4 Av-9 St",
        "15 St-Prospect Park",
        "Fort Hamilton Pkwy (F/G)",
        "Church Av (F/G)",
        "Ditmas Av",
        "18 Av (F)",
        "Avenue I",
        "Bay Pkwy (F)",
        "Avenue N",
        "Avenue P",
        "Kings Hwy (F)",
        "Avenue U (F)",
        "Avenue X",
        "Neptune Av",
        "Jamaica Center-Parsons/Archer",
        "Sutphin Blvd-Archer Av-JFK Airport",
        "Jamaica-Van Wyck",
        "Forest Hills-71 Av",
        "67 Av",
        "63 Dr-Rego Park",
        "Woodhaven Blvd (E/F/M/R)",
        "Grand Av-Newtown",
        "Elmhurst Av",
        "65 St",
        "Northern Blvd",
        "46 St",
        "Steinway St",
        "36 St (E/F/M/R)",
        "Queens Plaza",
        "21 St",
        "Greenpoint Av",
        "Nassau Av",
        "Metropolitan Av",
        "Broadway (G)",
        "Flushing Av (G)",
        "Myrtle-Willoughby Avs",
        "Bedford-Nostrand Avs",
        "Classon Av",
        "Clinton-Washington Avs (G)",
        "Fulton St (G)",
        "Aqueduct Racetrack",
        "Aqueduct-N Conduit Av",
        "Howard Beach-JFK Airport",
        "Broad Channel",
        "Beach 67 St",
        "Beach 60 St",
        "Beach 44 St",
        "Beach 36 St",
        "Beach 25 St",
        "Far Rockaway-Mott Av",
        "Beach 90 St",
        "Beach 98 St",
        "Beach 105 St",
        "Rockaway Park-Beach 116 St",
        "121 St",
        "111 St (J)",
        "104 St (J/Z)",
        "Woodhaven Blvd (J/Z)",
        "85 St-Forest Pkwy",
        "75 St-Elderts Ln",
        "Cypress Hills",
        "Crescent St",
        "Norwood Av",
        "Cleveland St",
        "Van Siclen Av (J/Z)",
        "Alabama Av",
        "Chauncey St",
        "Halsey St (J)",
        "Gates Av",
        "Kosciuszko St",
        "3 Av",
        "1 Av",
        "Bedford Av",
        "Graham Av",
        "Grand St (L)",
        "Montrose Av",
        "Morgan Av",
        "Jefferson St",
        "DeKalb Av (L)",
        "Myrtle-Wyckoff Avs",
        "Halsey St (L)",
        "Wilson Av",
        "Bushwick Av-Aberdeen St",
        "Atlantic Av",
        "Sutter Av",
        "New Lots Av (L)",
        "East 105 St",
        "Canarsie-Rockaway Pkwy",
        "Middle Village-Metropolitan Av",
        "Fresh Pond Rd",
        "Forest Av",
        "Seneca Av",
        "Knickerbocker Av",
        "Central Av",
        "Myrtle Av",
        "Flushing Av (J/M)",
        "Lorimer St",
        "Hewes St",
        "Marcy Av",
        "Bowery",
        "Broad St",
        "8 Av",
        "Fort Hamilton Pkwy (N/W)",
        "18 Av (N/W)",
        "20 Av (N/W)",
        "Bay Pkwy (N/W)",
        "Kings Hwy (N/W)",
        "Avenue U (N/W)",
        "86 St (N/W)",
        "72 St (N/Q/R)",
        "86 St (N/Q/R)",
        "96 St (N/Q/R)",
        "Astoria-Ditmars Blvd",
        "Astoria Blvd",
        "30 Av",
        "Broadway (N/W)",
        "36 Av",
        "39 Av-Dutch Kills",
        "5 Av/59 St",
        "57 St-7 Av",
        "49 St",
        "28 St (N/Q/R/W)",
        "23 St (N/Q/R/W)",
        "8 St",
        "Prince St",
        "City Hall",
        "Whitehall St-South Ferry",
        "DeKalb Av (B/D/N/Q/R/W)",
        "Union St",
        "Prospect Av (D/N/R/W)",
        "25 St",
        "36 St (D/N/R/W)",
        "45 St",
        "53 St",
        "59 St",
        "Bay Ridge Av",
        "77 St (R)",
        "86 St (R)",
        "Bay Ridge-95 St",
        "Park Pl",
        "Tottenville",
        "Arthur Kill",
        "Richmond Valley",
        "Pleasant Plains",
        "Prince's Bay",
        "Huguenot",
        "Annadale",
        "Eltingville",
        "Great Kills",
        "Bay Terrace",
        "Oakwood Heights",
        "New Dorp",
        "Grant City",
        "Jefferson Av",
        "Dongan Hills",
        "Old Town",
        "Grasmere",
        "Clifton (SIR)",
        "Stapleton",
        "Tompkinsville",
        "St George",

    ].sorted()
    
    // Station name to code mapping - Updated to match backend STATION_CODES.txt
    static let stationCodes: [String: String] = [
        // NJ Transit stations from authoritative STATION_CODES.txt
        "New York Penn Station": "NY",
        "Newark Penn Station": "NP",
        "Secaucus Upper Lvl": "SE",
        "Secaucus Lower Lvl": "TS",
        "Secaucus Concourse": "SC",
        "Woodbridge NJ": "WB",
        "Metropark": "MP",
        "New Brunswick": "NB",
        "Princeton Junction": "PJ",
        "Princeton": "PR",
        "Princeton NJ": "PR",
        "Trenton": "TR",
        "Trenton Transit Center": "TR",
        "Hamilton": "HL",
        "Morristown": "MR",
        "Madison NJ": "MA",
        "Summit NJ": "ST",
        "Millburn": "MB",
        "Short Hills": "RT",
        "Newark Airport": "NA",
        "Newark Broad Street": "ND",
        "Elizabeth": "EZ",
        "North Elizabeth": "NZ",
        "Linden": "LI",
        "Rahway": "RH",
        "Metuchen": "MU",
        "Edison": "ED",
        "Perth Amboy": "PE",
        "South Amboy": "CH",
        "Aberdeen-Matawan": "AM",
        "Hazlet": "HZ",
        "Middletown NJ": "MI",
        "Red Bank": "RB",
        "Little Silver": "LS",
        "Monmouth Park": "MK",
        "Long Branch": "LB",
        "Elberon": "EL",
        "Allenhurst": "AH",
        "Asbury Park": "AP",
        "Bradley Beach": "BB",
        "Belmar": "BS",
        "Spring Lake": "LA",
        "Manasquan": "SQ",
        "Point Pleasant Beach": "PP",
        "Bay Head": "BH",
        "Montclair State U": "UV",
        "Montclair Heights": "HS",
        "Upper Montclair": "UM",
        "Mountain Avenue": "MS",
        "Walnut Street": "WA",
        "Watchung Avenue": "WG",
        "Watsessing Avenue": "WT",
        "Orange": "OG",
        "East Orange": "EO",
        "Highland Avenue": "HI",
        "Mountain View": "MV",
        "Brick Church": "BU",
        "Bloomfield": "BM",
        "Glen Ridge": "GG",
        "Bay Street": "MC",
        "Ridgewood": "RW",
        "Ho-Ho-Kus": "UF",
        "Waldwick": "WK",
        "Allendale": "AZ",
        "Ramsey Route 17": "17",
        "Ramsey Main St": "RY",
        "Mahwah": "MZ",
        "Suffern": "SF",
        "Sloatsburg": "XG",
        "Tuxedo": "TC",
        "Harriman": "RM",
        "Campbell Hall": "CB",
        "Salisbury Mills-Cornwall": "CW",
        "Otisville": "OS",
        "Port Jervis": "PO",
        "Denville": "DV",
        "Dover": "DO",
        "Mount Tabor": "TB",
        "Mount Arlington": "HV",
        "Lake Hopatcong": "HP",
        "Netcong": "NT",
        "Mount Olive": "OL",
        "Hackettstown": "HQ",
        "Boonton": "BN",
        "Mountain Lakes": "ML",
        "Lincoln Park": "LP",
        "Towaco": "TO",
        "Montclair-Boonton Line": "MO",  // Generic
        "Little Falls": "FA",
        "Wayne-Route 23": "23",
        "Mountain Station": "MT",
        "Convent Station": "CN",
        "Chatham": "CM",
        "New Providence": "NV",
        "Murray Hill": "MH",
        "Berkeley Heights": "BY",
        "Gillette": "GI",
        "Stirling": "SG",
        "Millington": "GO",
        "Lyons": "LY",
        "Basking Ridge": "BI",
        "Bernardsville": "BV",
        "Far Hills": "FH",
        "Peapack": "PC",
        "Gladstone": "GL",
        "High Bridge": "HG",
        "Annandale": "AN",
        "Lebanon": "ON",
        "White House": "WH",
        "North Branch": "OR",
        "Raritan": "RA",
        "Somerville": "SM",
        "Bridgewater": "BW",
        "Bound Brook": "BK",
        "Dunellen": "DN",
        "Plainfield": "PF",
        "Netherwood": "NE",
        "Fanwood": "FW",
        "Westfield": "WF",
        "Garwood": "GW",
        "Cranford": "XC",
        "Roselle Park": "RL",
        "Union": "US",
        "Avenel": "AV",
        "Jersey Avenue": "JA",
        "Hoboken": "HB",
        "Kingsland": "KG",
        "Lyndhurst": "LN",
        "Delawanna": "DL",
        "Passaic": "PS",
        "Clifton": "IF",
        "Paterson": "RN",
        "Hawthorne": "HW",
        "Glen Rock Main Line": "RS",
        "Glen Rock Boro Hall": "GK",
        "Fair Lawn-Broadway": "BF",
        "Radburn Fair Lawn": "FZ",
        "Garfield": "GD",
        "Plauderville": "PL",
        "Rutherford": "RF",
        "Wood Ridge": "WR",
        "Wesmont": "WM",
        "Teterboro": "TE",
        "Essex Street": "EX",
        "Anderson Street": "AS",
        "New Bridge Landing": "NH",
        "River Edge": "RG",
        "Oradell": "OD",
        "Emerson": "EN",
        "Westwood": "WW",
        "Hillsdale": "HD",
        "Woodcliff Lake": "WL",
        "Park Ridge": "PV",
        "Montvale": "ZM",
        "Pearl River": "PQ",
        "Nanuet": "NN",
        "Spring Valley": "SV",
        "Maplewood": "MW",
        "South Orange": "SO",
        "Morris Plains": "MX",
        "Great Notch": "GA",

        // Atlantic City Line
        "Pennsauken": "PN",
        "Cherry Hill": "CY",
        "Lindenwold NJT": "LW",
        "Atco": "AO",
        "Hammonton": "HN",
        "Egg Harbor City": "EH",
        "Absecon": "AB",
        "Atlantic City Rail Terminal": "AC",

        // PATH stations (3-char codes to match API constraints)
        "Newark PATH": "PNK",
        "Harrison PATH": "PHR",
        "Journal Square": "PJS",
        "Grove Street": "PGR",
        "Exchange Place": "PEX",
        "Newport": "PNP",
        "Hoboken PATH": "PHO",
        "Christopher Street": "PCH",
        "9th Street": "P9S",
        "14th Street": "P14",
        "23rd Street": "P23",
        "33rd Street": "P33",
        "World Trade Center": "PWC",

        // PATCO Speedline stations (Philadelphia - South Jersey)
        "Lindenwold": "LND",
        "Ashland PATCO": "ASD",
        "Woodcrest": "WCT",
        "Haddonfield": "HDF",
        "Westmont": "WMT",
        "Collingswood": "CLD",
        "Ferry Avenue": "FRY",
        "Broadway PATCO": "BWY",
        "City Hall PATCO": "CTH",
        "Franklin Square": "FKS",
        "8th and Market": "EMK",
        "9-10th and Locust": "NTL",
        "12-13th and Locust": "TWL",
        "15-16th and Locust": "FFL",

        // Missing Keystone Service stations (PA)
        "Middletown PA": "MIDPA",  // Renamed to avoid conflict with Middletown NJ
        "Elizabethtown": "ELT",
        "Mount Joy": "MJY",
        "Parkesburg": "PAR",
        "Coatesville": "COT",
        "Downingtown": "DOW",
        "Exton": "EXT",
        "Paoli": "PAO",
        
        // Amtrak stations (corrected with updated codes to match backend)
        "Boston South": "BOS",
        "Boston Back Bay": "BBY",
        "Providence": "PVD",
        "Hartford": "HFD",
        "Meriden": "MDN",
        "New London": "NLC",
        "Old Saybrook": "OSB",
        "Wallingford": "WFD",
        "Windsor Locks": "WNL",
        "Springfield MA": "SPG",
        "Claremont NH": "CLA",
        "Dover NH": "DOV",  // Renamed to avoid conflict with Dover NJ
        "Durham-UNH": "DHM",
        "Exeter": "EXR",
        "Philadelphia": "PH",
        "Baltimore Station": "BL",
        "Washington Union Station": "WS",
        "BWI Thurgood Marshall Airport": "BA",
        "Wilmington DE": "WI",
        "New Carrollton": "NCR",
        "Aberdeen": "ABE",
        "Alexandria": "ALX",
        "Charlottesville": "CVS",
        "Lorton": "LOR",
        "Manassas": "MSS",
        "Norfolk": "NFK",
        "Richmond Main Street": "RVM",
        "Richmond Staples Mill Road": "RVR",
        "Roanoke": "RNK",
        "Harrisburg": "HAR",
        "Lancaster": "LNC",
        "Kingston": "KIN",
        "Westerly": "WLY",

        // LIRR stations (Long Island Rail Road)
        // Note: Penn Station maps to "NY" for unified experience with NJT/Amtrak
        // Atlantic Terminal uses "LAT" to avoid conflict with Atlanta "ATL"
        "Albertson": "ABT",
        "Amagansett": "AGT",
        "Amityville": "AVL",
        "Atlantic Terminal": "LAT",
        "Auburndale": "ADL",
        "Babylon": "BTA",
        "Baldwin": "BWN",
        "Bay Shore": "BSR",
        "Bayside": "BSD",
        "Bellerose": "BRS",
        "Bellmore": "BMR",
        "Bellport": "BPT",
        "Belmont Park": "BRT",
        "Bethpage": "BPG",
        "Brentwood": "BWD",
        "Bridgehampton": "BHN",
        "Broadway LIRR": "BDY",
        "Carle Place": "CPL",
        "Cedarhurst": "CHT",
        "Central Islip": "CI",
        "Centre Avenue": "CAV",
        "Cold Spring Harbor": "CSH",
        "Copiague": "CPG",
        "Country Life Press": "LCLP",
        "Deer Park": "DPK",
        "Douglaston": "DGL",
        "East Hampton": "EHN",
        "East New York": "ENY",
        "East Rockaway": "ERY",
        "East Williston": "EWN",
        "Elmont-UBS Arena": "EMT",
        "Far Rockaway": "LFRY",
        "Farmingdale": "LFMD",
        "Floral Park": "FPK",
        "Flushing Main Street": "FLS",
        "Forest Hills": "FHL",
        "Freeport": "FPT",
        "Garden City": "GCY",
        "Gibson": "GBN",
        "Glen Cove": "GCV",
        "Glen Head": "GHD",
        "Glen Street": "GST",
        "Great Neck": "GNK",
        "Great River": "GRV",
        "Greenlawn": "GWN",
        "Greenport": "GPT",
        "Greenvale": "LGVL",
        "Hampton Bays": "HBY",
        "Hempstead Gardens": "HGN",
        "Hempstead": "LHEM",
        "Hewlett": "HWT",
        "Hicksville": "LHVL",
        "Hollis": "LHOL",
        "Hunterspoint Avenue": "HPA",
        "Huntington": "LHUN",
        "Inwood": "IWD",
        "Island Park": "IPK",
        "Islip": "ISP",
        "Jamaica": "JAM",
        "Kew Gardens": "KGN",
        "Kings Park": "KPK",
        "Lakeview": "LLVW",
        "Laurelton": "LTN",
        "Lawrence": "LCE",
        "Lindenhurst": "LHT",
        "Little Neck": "LLNK",
        "Locust Manor": "LLMR",
        "Locust Valley": "LVL",
        "Long Beach": "LBH",
        "Long Island City": "LIC",
        "Lynbrook": "LYN",
        "Malverne": "LMVN",
        "Manhasset": "MHT",
        "Massapequa Park": "LMPK",
        "Massapequa": "MQA",
        "Mastic-Shirley": "MSY",
        "Mattituck": "MAK",
        "Medford": "MFD",
        "Merillon Avenue": "MAV",
        "Merrick": "MRK",
        "Mets-Willets Point": "LSSM",
        "Mineola": "LMIN",
        "Montauk": "MTK",
        "Murray Hill LIRR": "LMHL",
        "Nassau Boulevard": "NBD",
        "New Hyde Park": "NHP",
        "Northport": "NPT",
        "Nostrand Avenue": "NAV",
        "Oakdale": "ODL",
        "Oceanside": "ODE",
        "Oyster Bay": "OBY",
        "Patchogue": "PGE",
        "Pinelawn": "PLN",
        "Plandome": "PDM",
        "Port Jefferson": "PJN",
        "Port Washington": "PWS",
        "Queens Village": "QVG",
        "Riverhead": "RHD",
        "Rockville Centre": "RVC",
        "Ronkonkoma": "RON",
        "Rosedale": "ROS",
        "Roslyn": "RSN",
        "Sayville": "SVL",
        "Sea Cliff": "SCF",
        "Seaford": "SFD",
        "Smithtown": "LSTN",
        "Southampton": "SHN",
        "Southold": "SHD",
        "Speonk": "LSPK",
        "St. Albans": "LSAB",
        "St. James": "LSJM",
        "Stewart Manor": "SMR",
        "Stony Brook": "LSBK",
        "Syosset": "SYT",
        "Valley Stream": "VSM",
        "Wantagh": "WGH",
        "West Hempstead": "WHD",
        "Westbury": "WBY",
        "Westhampton": "WHN",
        "Westwood LIRR": "LWWD",
        "Woodmere": "WMR",
        "Woodside": "WDD",
        "Wyandanch": "WYD",
        "Yaphank": "YPK",

        // Metro-North Railroad stations
        "Grand Central Terminal": "GCT",
        "Harlem-125th Street": "M125",
        "Yankees-E 153 St": "MEYS",
        "Morris Heights": "MMRH",
        "University Heights": "MUNH",
        "Marble Hill": "MMBL",
        "Spuyten Duyvil": "MSDV",
        "Riverdale": "MRVD",
        "Ludlow": "MLUD",
        "Yonkers": "MYON",
        "Glenwood": "MGWD",
        "Greystone": "MGRY",
        "Hastings-on-Hudson": "MHOH",
        "Dobbs Ferry": "MDBF",
        "Ardsley-on-Hudson": "MARD",
        "Irvington": "MIRV",
        "Tarrytown": "MTTN",
        "Philipse Manor": "MPHM",
        "Scarborough": "MSCB",
        "Ossining": "MOSS",
        "Croton-Harmon": "MCRH",
        "Cortlandt": "MCRT",
        "Peekskill": "MPKS",
        "Manitou": "MMAN",
        "Garrison": "MGAR",
        "Cold Spring": "MCSP",
        "Breakneck Ridge": "MBRK",
        "Beacon": "MBCN",
        "New Hamburg": "MNHB",
        "Poughkeepsie": "MPOK",
        "Melrose": "MMEL",
        "Tremont": "MTRM",
        "Fordham": "MFOR",
        "Botanical Garden": "MBOG",
        "Williams Bridge": "MWBG",
        "Woodlawn": "MWDL",
        "Wakefield": "MWKF",
        "Mt Vernon West": "MMVW",
        "Fleetwood": "MFLT",
        "Bronxville": "MBRX",
        "Tuckahoe": "MTUC",
        "Crestwood": "MCWD",
        "Scarsdale": "MSCD",
        "Hartsdale": "MHSD",
        "White Plains": "MWPL",
        "North White Plains": "MNWP",
        "Valhalla": "MVAL",
        "Mt Pleasant": "MMTP",
        "Hawthorne NY": "MHWT",
        "Pleasantville": "MPLV",
        "Chappaqua": "MCHP",
        "Mt Kisco": "MMTK",
        "Bedford Hills": "MBDH",
        "Katonah": "MKAT",
        "Goldens Bridge": "MGLD",
        "Purdys": "MPRD",
        "Croton Falls": "MCFL",
        "Brewster": "MBRS",
        "Southeast": "MSET",
        "Patterson": "MPAT",
        "Pawling": "MPAW",
        "Appalachian Trail": "MAPT",
        "Harlem Valley-Wingdale": "MHVW",
        "Dover Plains": "MDVP",
        "Tenmile River": "MTMR",
        "Wassaic": "MWAS",
        "Mt Vernon East": "MMVE",
        "Pelham": "MPEL",
        "New Rochelle": "MNRC",
        "Larchmont": "MLRM",
        "Mamaroneck": "MMAM",
        "Harrison": "MHRR",
        "Rye": "MRYE",
        "Port Chester": "MPCH",
        "Greenwich": "MGRN",
        "Cos Cob": "MCOC",
        "Riverside": "MRSD",
        "Old Greenwich": "MODG",
        "Stamford": "MSTM",
        "Noroton Heights": "MNOH",
        "Darien": "MDAR",
        "Rowayton": "MROW",
        "South Norwalk": "MSNW",
        "East Norwalk": "MENW",
        "Westport": "MWPT",
        "Greens Farms": "MGRF",
        "Southport": "MSPT",
        "Fairfield": "MFFD",
        "Fairfield-Black Rock": "MFBR",
        "Bridgeport": "MBGP",
        "Stratford": "MSTR",
        "Milford": "MMIL",
        "West Haven": "MWHN",
        "New Haven": "MNHV",
        "New Haven-State St": "MNSS",
        "Glenbrook": "MGLB",
        "Springdale": "MSPD",
        "Talmadge Hill": "MTMH",
        "New Canaan": "MNCA",
        "Merritt 7": "MMR7",
        "Wilton": "MWIL",
        "Cannondale": "MCAN",
        "Branchville": "MBVL",
        "Redding": "MRED",
        "Bethel": "MBTH",
        "Danbury": "MDBY",
        "Derby-Shelton": "MDBS",
        "Ansonia": "MANS",
        "Seymour": "MSYM",
        "Beacon Falls": "MBCF",
        "Naugatuck": "MNAU",
        "Waterbury": "MWTB",

        // Southeast Amtrak stations
        "Charlotte": "CLT",
        "Raleigh": "RGH",
        "Greensboro NC": "GRB",
        "Durham": "DNC",
        "Rocky Mount": "RMT",
        "Wilson": "WLN",
        "Cary NC": "CAR",
        "Southern Pines NC": "SOU",
        "High Point": "HPT",
        "Salisbury": "SAL",
        "Gastonia": "GAS",
        "Hamlet": "HAM",
        "Selma-Smithfield": "SEL",
        "Petersburg": "PTB",
        "Charleston SC": "CHS",
        "Spartanburg": "SPB",
        "Greenville": "GVL",
        "Kingstree": "KTR",
        "Florence": "FLO",
        "Dillon": "DIL",
        "Clemson": "CSN",
        "Savannah": "SAV",
        "Atlanta": "ATL",
        "Jesup GA": "JES",
        "Gainesville GA": "GAI",
        "Toccoa GA": "TOC",
        "Jacksonville": "JAX",
        "Miami": "MIA",
        "Orlando": "ORL",
        "Tampa": "TPA",
        "Fort Lauderdale": "FTL",
        "West Palm Beach": "WPB",
        "Kissimmee": "KIS",
        "Lakeland FL": "LKL",
        "Winter Park FL": "WPK",
        "DeLand": "DLD",
        "Sanford FL": "SAN",
        "Hollywood FL": "HLW",
        "Delray Beach": "DLB",
        "Waldo FL": "WLD",
        "Ocala": "OCA",
        "Winter Haven": "WTH",
        "Palatka FL": "PAL",
        "Thurmond WV": "THU",
        // Nationwide Amtrak stations
        "Chicago Union Station": "CHI",
        "St. Louis": "STL",
        "Milwaukee": "MKE",
        "Los Angeles Union Station": "LAX",
        "Seattle King Street": "SEA",
        "Portland Union Station": "PDX",
        "Emeryville": "EMY",
        "Sacramento": "SAC",
        "New Orleans": "NOL",
        "San Antonio": "SAS",
        "Denver Union Station": "DEN",
        // California / Southwest
        "Santa Barbara": "SBA",
        "San Luis Obispo": "SLO",
        "San Jose": "SJC",
        "Oceanside CA": "OSD",
        "Santa Ana": "SNA",
        "Fullerton": "FUL",
        "San Diego Old Town": "OLT",
        "Albuquerque": "ABQ",
        "Flagstaff": "FLG",
        "Tucson": "TUS",
        "El Paso": "ELP",
        "Reno": "RNO",
        "Truckee": "TRU",
        // Pacific Northwest
        "Spokane": "SPK",
        "Tacoma": "TAC",
        "Eugene": "EUG",
        "Salem OR": "SLM",
        "Salt Lake City": "SLC",
        "Whitefish": "WFH",
        "East Glacier Park": "GPK",
        "Havre": "HAV",
        "St. Paul-Minneapolis": "MSP",
        // Texas / South Central
        "Dallas": "DAL",
        "Fort Worth": "FTW",
        "Houston": "HOS",
        "Austin": "AUS",
        "Little Rock": "LRK",
        "Memphis": "MEM",
        // Midwest / Great Lakes
        "Kansas City": "KCY",
        "Oklahoma City": "OKC",
        "Omaha": "OMA",
        "Indianapolis": "IND",
        "Cincinnati": "CIN",
        "Cleveland": "CLE",
        "Toledo": "TOL",
        "Detroit": "DET",
        "Grand Rapids": "GRR",
        "Pittsburgh": "PGH",
        // Northeast extensions
        "Albany-Rensselaer": "ALB",
        "Syracuse": "SYR",
        "Rochester": "ROC",
        "Buffalo Depew": "BUF",
        "Montreal": "MTR",
        "Portland ME": "POR",
        "Essex Junction": "ESX",
        "Burlington VT": "BTN",
        // Virginia / Southeast
        "Lynchburg": "LYH",
        "Newport News": "NPN",
        "Williamsburg VA": "WBG",
        "Columbia SC": "CLB",
        "Birmingham": "BHM",
        "Mobile": "MOE",

        // California
        "Anaheim": "ANA",
        "Arcata CA": "ARC",
        "Auburn": "ARN",
        "Barstow": "BAR",
        "Burbank Airport": "BBK",
        "Bakersfield": "BFD",
        "Berkeley": "BKY",
        "Burbank Downtown": "BUR",
        "Chico": "CIC",
        "Claremont CA": "CLM",
        "Camarillo": "CML",
        "Colfax": "COX",
        "Carpinteria": "CPN",
        "Chatsworth": "CWT",
        "Davis": "DAV",
        "Dublin-Pleasanton": "DBP",
        "Dunsmuir": "DUN",
        "Elko": "ELK",
        "Fairfield-Vacaville": "FFV",
        "Fremont": "FMT",
        "Fresno": "FNO",
        "Santa Clara Great America": "GAC",
        "Glendale": "GDL",
        "Gilroy": "GLY",
        "Goleta": "GTA",
        "Guadalupe": "GUA",
        "Grover Beach": "GVB",
        "Hayward": "HAY",
        "Hanford": "HNF",
        "Arcata-Humboldt State": "HSU",
        "Irvine": "IRV",
        "Lodi": "LOD",
        "Lompoc-Surf": "LPS",
        "Las Vegas NV": "LVS",
        "Merced": "MCD",
        "Moorpark": "MPK",
        "Marysville": "MRV",
        "Martinez": "MTZ",
        "Seaside-Marina": "MYU",
        "Santa Clarita-Newhall": "NHL",
        "Northridge": "NRG",
        "Oakland Coliseum/Airport": "OAC",
        "Oakland": "OKJ",
        "Ontario": "ONA",
        "Oxnard": "OXN",
        "Pomona": "POS",
        "Paso Robles": "PRB",
        "Palm Springs": "PSN",
        "Petaluma": "PTC",
        "Redding CA": "RDD",
        "Richmond": "RIC",
        "Riverside CA": "RIV",
        "Rocklin": "RLN",
        "Roseville": "RSV",
        "Santa Clara": "SCC",
        "San Francisco": "SFC",
        "Simi Valley": "SIM",
        "Stockton ACE": "SKN",
        "Stockton San Joaquins": "SKT",
        "Santa Monica Pier": "SMN",
        "San Bernardino": "SNB",
        "San Juan Capistrano": "SNC",
        "San Clemente Pier": "SNP",
        "Salinas": "SNS",
        "Solana Beach": "SOL",
        "Suisun-Fairfield": "SUI",
        "Vallejo": "VAL",
        "Ventura": "VEC",
        "Van Nuys": "VNC",
        "Victorville": "VRV",
        "Winnemucca": "WNN",
        "Willits Calif Western Railroad Depot": "WTS",

        // Great Lakes
        "Albion": "ALI",
        "Ann Arbor": "ARB",
        "Bangor": "BAM",
        "Battle Creek": "BTL",
        "Columbus": "CBS",
        "Dearborn": "DER",
        "Durand": "DRD",
        "Erie": "ERI",
        "Flint": "FLN",
        "Glenview": "GLN",
        "Holland": "HOM",
        "Jackson MI": "JXN",
        "Kalamazoo": "KAL",
        "East Lansing": "LNS",
        "Lapeer": "LPE",
        "General Mitchell Intl. Airport": "MKA",
        "Pontiac MI": "PNT",
        "Portage": "POG",
        "Port Huron": "PTH",
        "Royal Oak": "ROY",
        "St. Joseph-Benton Harbor": "SJM",
        "Sturtevant": "SVT",
        "Troy": "TRM",
        "Wisconsin Dells": "WDL",

        // Mid-Atlantic
        "Altoona": "ALT",
        "Ardmore PA": "ARD",
        "Berlin": "BER",
        "Branford": "BNF",
        "Bowie State": "BWE",
        "Clinton": "CLN",
        "Connellsville": "COV",
        "Cumberland": "CUM",
        "Cornwells Heights": "CWH",
        "Edgewood": "EDG",
        "Greensburg": "GNB",
        "Guilford": "GUI",
        "Halethorpe": "HAE",
        "Harpers Ferry": "HFY",
        "Huntingdon": "HGD",
        "Johnstown": "JST",
        "Latrobe": "LAB",
        "Lewistown": "LEW",
        "Madison CT": "MDS",
        "Middletown CT": "MID",
        "Martinsburg": "MRB",
        "Martin Airport": "MSA",
        "Mystic": "MYS",
        "Newark": "NRK",
        "Odenton": "OTN",
        "Parkesburg PA": "PAR",
        "North Philadelphia": "PHN",
        "Perryville": "PRV",
        "Rhinecliff": "RHI",
        "Rockville": "RKV",
        "New Haven State St": "STS",
        "Tyrone": "TYR",
        "West Baltimore": "WBL",
        "Windsor": "WND",
        "Westbrook": "WSB",

        // Midwest
        "Ashland KY": "AKY",
        "Alliance": "ALC",
        "Alderson": "ALD",
        "Bloomington-Normal": "BNL",
        "Bryan": "BYN",
        "Carbondale": "CDL",
        "Centralia IL": "CEN",
        "Champaign-Urbana": "CHM",
        "Charleston WV": "CHW",
        "Connersville": "COI",
        "Crawfordsville": "CRF",
        "Carlinville": "CRV",
        "Dowagiac": "DOA",
        "Du Quoin": "DQN",
        "Dwight": "DWT",
        "Dyer": "DYE",
        "Effingham": "EFG",
        "Elkhart": "EKH",
        "Elyria": "ELY",
        "Fulton": "FTN",
        "Gilman": "GLM",
        "Hinton": "HIN",
        "Hammond-Whiting": "HMI",
        "Homewood": "HMW",
        "Huntington WV": "HUN",
        "Joliet Gateway Center": "JOL",
        "Kannapolis": "KAN",
        "Kewanee": "KEE",
        "Kankakee": "KKI",
        "Lafayette IN": "LAF",
        "La Grange": "LAG",
        "Lincoln IL": "LCN",
        "Mattoon": "MAT",
        "Maysville": "MAY",
        "Mendota": "MDT",
        "Montgomery": "MNG",
        "Newbern-Dyersburg": "NBN",
        "New Buffalo": "NBU",
        "Niles": "NLS",
        "Naperville": "NPV",
        "Princeton IL": "PCT",
        "Peoria": "PIA",
        "Plano": "PLO",
        "Pontiac IL": "PON",
        "Prince": "PRC",
        "Rensselaer": "REN",
        "Rantoul": "RTL",
        "Sandusky": "SKY",
        "Summit IL": "SMT",
        "South Bend": "SOB",
        "Springfield IL": "SPI",
        "South Portsmouth": "SPM",
        "Thurmond WV Alt": "THN",
        "White Sulphur Springs": "WSS",
        "Waterloo": "WTI",

        // Mountain West
        "Arcadia Valley": "ACD",
        "Ardmore OK": "ADM",
        "Alton": "ALN",
        "Alpine": "ALP",
        "Arkadelphia": "ARK",
        "Beaumont": "BMT",
        "Brookhaven": "BRH",
        "Burlington IA": "BRL",
        "Cleburne": "CBR",
        "Creston": "CRN",
        "Dodge City": "DDG",
        "Detroit Lakes": "DLK",
        "Del Rio": "DRT",
        "Devils Lake": "DVL",
        "Fargo": "FAR",
        "Fort Madison": "FMD",
        "Fort Morgan": "FMG",
        "Galesburg": "GBB",
        "Garden City KS": "GCK",
        "Grand Forks": "GFK",
        "Gainesville TX": "GLE",
        "Greenwood": "GWD",
        "Hastings": "HAS",
        "Hazlehurst": "HAZ",
        "Hermann": "HEM",
        "Holdrege": "HLD",
        "Hammond": "HMD",
        "Hope": "HOP",
        "Hutchinson": "HUT",
        "Independence": "IDP",
        "Jackson MS": "JAN",
        "Jefferson City": "JEF",
        "Killeen": "KIL",
        "Kirkwood": "KWD",
        "La Junta": "LAJ",
        "La Plata": "LAP",
        "Lbo": "LBO",
        "Lake Charles": "LCH",
        "Lee'S Summit": "LEE",
        "Lafayette LA": "LFT",
        "Lamar": "LMR",
        "Lincoln NE": "LNK",
        "Lawrence KS": "LRC",
        "La Crosse": "LSE",
        "Longview": "LVW",
        "Macomb": "MAC",
        "Mccomb": "MCB",
        "Mcgregor": "MCG",
        "Mccook": "MCK",
        "Marshall": "MHL",
        "Mineola TX": "MIN",
        "Marks": "MKS",
        "Minot": "MOT",
        "Mt. Pleasant": "MTP",
        "Malvern": "MVN",
        "New Iberia": "NIB",
        "Norman": "NOR",
        "Osceola": "OSC",
        "Ottumwa": "OTM",
        "Poplar Bluff": "PBF",
        "Purcell": "PUR",
        "Pauls Valley": "PVL",
        "Quincy": "QCY",
        "Raton": "RAT",
        "Red Wing": "RDW",
        "Rugby": "RUG",
        "St. Cloud": "SCD",
        "Schriever": "SCH",
        "Sedalia": "SED",
        "Shreveport Sportran Intermodal Terminal": "SHR",
        "San Marcos": "SMC",
        "Sanderson": "SND",
        "Staples": "SPL",
        "Stanley": "STN",
        "Taylor": "TAY",
        "Tomah": "TOH",
        "Topeka": "TOP",
        "Temple": "TPL",
        "Trinidad": "TRI",
        "Texarkana": "TXA",
        "Washington": "WAH",
        "Warrensburg": "WAR",
        "Wellington": "WEL",
        "Wichita": "WIC",
        "Winona": "WIN",
        "Walnut Ridge": "WNR",
        "Williston": "WTN",
        "Yazoo City": "YAZ",

        // New England
        "Amsterdam": "AMS",
        "Aldershot": "AST",
        "Buffalo": "BFX",
        "Bellows Falls": "BLF",
        "Boston North": "BON",
        "Brattleboro": "BRA",
        "Brunswick": "BRK",
        "Canadian Border": "CBN",
        "Castleton": "CNV",
        "Fort Edward": "FED",
        "Framingham": "FRA",
        "Freeport ME": "FRE",
        "Ticonderoga": "FTC",
        "Greenfield": "GFD",
        "Grimsby": "GMS",
        "Haverhill": "HHL",
        "Holyoke": "HLK",
        "Hudson": "HUD",
        "Middlebury": "MBY",
        "Montpelier-Berlin": "MPR",
        "Niagara Falls NY": "NFL",
        "Niagara Falls ON": "NFS",
        "Northampton": "NHT",
        "Oakville": "OKL",
        "Old Orchard Beach": "ORB",
        "Pittsfield": "PIT",
        "Plattsburgh": "PLB",
        "Port Henry": "POH",
        "Rome": "ROM",
        "Randolph": "RPH",
        "Rouses Point": "RSP",
        "Route 128": "RTE",
        "Rutland": "RUD",
        "St. Albans VT": "SAB",
        "Saco": "SAO",
        "Saratoga Springs": "SAR",
        "St. Catherines": "SCA",
        "Schenectady": "SDY",
        "St-Lambert": "SLQ",
        "Toronto": "TWO",
        "Utica": "UCA",
        "Ferrisburgh": "VRN",
        "Waterbury-Stowe": "WAB",
        "Wells": "WEM",
        "Whitehall": "WHL",
        "Windsor-Mt. Ascutney": "WNM",
        "Woburn": "WOB",
        "Worcester Union": "WOR",
        "White River Junction": "WRJ",
        "Westport Alt": "WSP",

        // Pacific Northwest
        "Albany": "ALY",
        "Bellingham": "BEL",
        "Bingen-White Salmon": "BNG",
        "Browning": "BRO",
        "Chemult": "CMO",
        "Centralia WA": "CTL",
        "Cut Bank": "CUT",
        "Edmonds": "EDM",
        "Ephrata": "EPH",
        "Essex": "ESM",
        "Everett": "EVR",
        "Glasgow": "GGW",
        "Granby": "GRA",
        "Kelso-Longview": "KEL",
        "Klamath Falls": "KFS",
        "Libby": "LIB",
        "Leavenworth": "LWA",
        "Malta": "MAL",
        "Mount Vernon": "MVW",
        "Olympia-Lacey": "OLW",
        "Oregon City": "ORC",
        "Provo": "PRO",
        "Pasco": "PSC",
        "Shelby": "SBY",
        "Sandpoint": "SPT",
        "Stanwood": "STW",
        "Tukwila": "TUK",
        "Vancouver BC": "VAC",
        "Vancouver WA": "VAN",
        "Wenatchee": "WEN",
        "West Glacier": "WGL",
        "Wishram": "WIH",
        "Wolf Point": "WPT",

        // South Central
        "Anniston": "ATN",
        "Bay St Louis": "BAS",
        "Bradenton": "BDT",
        "Biloxi Amtrak Sta": "BIX",
        "Camden": "CAM",
        "Deerfield Beach": "DFB",
        "Denmark": "DNK",
        "Gainesville FL": "GNS",
        "Gulfport Amtrak Sta": "GUF",
        "Hattiesburg": "HBG",
        "Hollywood": "HOL",
        "Jesup GA Alt": "JSP",
        "Lakeland FL Alt": "LAK",
        "Laurel": "LAU",
        "Meridian Union": "MEI",
        "Okeechobee": "OKE",
        "Pascagoula": "PAG",
        "Palatka FL Alt": "PAK",
        "Picayune": "PIC",
        "Sebring": "SBG",
        "Slidell": "SDL",
        "Sanford Amtrak Auto Train": "SFA",
        "St. Petersburg": "STP",
        "Toccoa GA Alt": "TCA",
        "Tuscaloosa": "TCL",
        "Waldo FL Alt": "WDO",
        "Wildwood": "WWD",
        "Yemassee": "YEM",

        // Southeast
        "Burke Centre": "BCV",
        "Burlington NC": "BNC",
        "Clifton Forge": "CLF",
        "Culpeper": "CLP",
        "Cary NC Alt": "CYN",
        "Danville": "DAN",
        "Fayetteville": "FAY",
        "Fredericksburg": "FBG",
        "Goldsboro": "GBO",
        "Greensboro NC Alt": "GRO",
        "Havelock": "HVL",
        "Kinston": "KNC",
        "Morehead City": "MHD",
        "Quantico": "QAN",
        "Seabrook": "SEB",
        "Southern Pines NC Alt": "SOP",
        "Selma": "SSM",
        "Staunton": "STA",
        "Swansboro": "SWB",
        "Woodbridge VA": "WDB",
        "Wilmington NC": "WMN",

        // Southwest
        "Benson": "BEN",
        "Deming": "DEM",
        "Grand Junction": "GJT",
        "Gallup": "GLP",
        "Green River": "GRI",
        "Glenwood Springs": "GSC",
        "Helper": "HER",
        "Kingman": "KNG",
        "Lordsburg": "LDB",
        "Lamy": "LMY",
        "Las Vegas NM": "LSV",
        "Maricopa": "MRC",
        "Needles": "NDL",
        "Phoenix Sky Harbor Airport": "PHA",
        "North Phoenix Metro Center Transit": "PXN",
        "Santa Fe": "SAF",
        "Winter Park/Fraser": "WIP",
        "Winslow": "WLO",
        "Williams": "WMH",
        "Winter Park Ski Resort": "WPR",
        "Winter Park": "WPS",
        "Yuma": "YUM",

        // NYC Subway Stations (consolidated — canonical codes only)
        "Van Cortlandt Park-242 St": "S101",
        "238 St": "S103",
        "231 St": "S104",
        "Marble Hill-225 St": "S106",
        "215 St": "S107",
        "207 St": "S108",
        "Dyckman St": "S109",
        "191 St": "S110",
        "181 St": "S111",
        "168 St": "S112",
        "157 St": "S113",
        "145 St": "S114",
        "137 St-City College": "S115",
        "125 St": "S116",
        "116 St-Columbia University": "S117",
        "Cathedral Pkwy (110 St)": "S118",
        "103 St (1/A/B/C)": "S119",
        "96 St (1/2/3/A/B/C)": "S120",
        "86 St (1/2)": "S121",
        "79 St (1/2)": "S122",
        "72 St (1/2/3)": "S123",
        "66 St-Lincoln Center": "S124",
        "59 St-Columbus Circle": "S125",
        "50 St (1/2/A/C/E)": "S126",
        "Times Sq-42 St": "S127",
        "34 St-Penn Station": "S128",
        "28 St (1/2)": "S129",
        "23 St (1/2)": "S130",
        "18 St": "S131",
        "14 St (1/2/3/F/L/M)": "S132",
        "Christopher St-Stonewall": "S133",
        "Houston St": "S134",
        "Canal St": "S135",
        "Franklin St": "S136",
        "Chambers St": "S137",
        "Rector St (1)": "S139",
        "South Ferry": "S142",
        "Wakefield-241 St": "S201",
        "Nereid Av": "S204",
        "233 St": "S205",
        "225 St": "S206",
        "219 St": "S207",
        "Gun Hill Rd": "S208",
        "Burke Av": "S209",
        "Allerton Av": "S210",
        "Pelham Pkwy": "S211",
        "Bronx Park East": "S212",
        "E 180 St": "S213",
        "West Farms Sq-E Tremont Av": "S214",
        "174 St": "S215",
        "Freeman St": "S216",
        "Simpson St": "S217",
        "Intervale Av": "S218",
        "Prospect Av (2/5)": "S219",
        "Jackson Av": "S220",
        "3 Av-149 St": "S221",
        "149 St-Grand Concourse": "S222",
        "135 St (2/3)": "S224",
        "116 St (2/3)": "S226",
        "110 St-Malcolm X Plaza": "S227",
        "Chambers St-WTC": "S228",
        "Fulton St (2/3/4/5/A/C/J/Z)": "S229",
        "Wall St (2/3)": "S230",
        "Clark St": "S231",
        "Borough Hall": "S232",
        "Hoyt St": "S233",
        "Nevins St": "S234",
        "Atlantic Av-Barclays Ctr": "S235",
        "Bergen St (2/3/4)": "S236",
        "Grand Army Plaza": "S237",
        "Eastern Pkwy-Brooklyn Museum": "S238",
        "Franklin Av (2/3/4/5/FS)": "S239",
        "President St-Medgar Evers College": "S241",
        "Sterling St": "S242",
        "Winthrop St": "S243",
        "Church Av (2/5)": "S244",
        "Beverly Rd": "S245",
        "Newkirk Av-Little Haiti": "S246",
        "Flatbush Av-Brooklyn College": "S247",
        "Nostrand Av (2/3/4/5)": "S248",
        "Kingston Av": "S249",
        "Crown Hts-Utica Av": "S250",
        "Sutter Av-Rutland Rd": "S251",
        "Saratoga Av": "S252",
        "Rockaway Av (2/3/4/5)": "S253",
        "Livonia Av": "S254",
        "Pennsylvania Av": "S255",
        "Van Siclen Av (2/3/4/5)": "S256",
        "New Lots Av (2/3/4/5)": "S257",
        "Harlem-148 St": "S301",
        "Woodlawn (4)": "S401",
        "Mosholu Pkwy": "S402",
        "Bedford Park Blvd-Lehman College": "S405",
        "Kingsbridge Rd (4)": "S406",
        "Fordham Rd (4)": "S407",
        "183 St": "S408",
        "Burnside Av": "S409",
        "176 St": "S410",
        "Mt Eden Av": "S411",
        "170 St (4)": "S412",
        "167 St (4)": "S413",
        "161 St-Yankee Stadium": "S414",
        "138 St-Grand Concourse": "S416",
        "Wall St (4/5)": "S419",
        "Bowling Green": "S420",
        "Eastchester-Dyre Av": "S501",
        "Baychester Av": "S502",
        "Morris Park": "S505",
        "Pelham Bay Park": "S601",
        "Buhre Av": "S602",
        "Middletown Rd": "S603",
        "Westchester Sq-E Tremont Av": "S604",
        "Zerega Av": "S606",
        "Castle Hill Av": "S607",
        "Parkchester": "S608",
        "St Lawrence Av": "S609",
        "Morrison Av-Soundview": "S610",
        "Elder Av": "S611",
        "Whitlock Av": "S612",
        "Hunts Point Av": "S613",
        "Longwood Av": "S614",
        "E 149 St": "S615",
        "E 143 St-St Mary's St": "S616",
        "Cypress Av": "S617",
        "Brook Av": "S618",
        "3 Av-138 St": "S619",


        "116 St (4/6)": "S622",
        "110 St": "S623",
        "103 St (4/6)": "S624",
        "96 St (4/6)": "S625",
        "86 St (4/5/6)": "S626",
        "77 St (4/6)": "S627",
        "68 St-Hunter College": "S628",
        "Lexington Av/59 St": "S629",
        "Lexington Av/53 St": "S630",
        "Grand Central-42 St": "S631",
        "33 St": "S632",
        "28 St (4/6)": "S633",
        "23 St-Baruch College": "S634",
        "14 St-Union Sq": "S635",
        "Astor Pl": "S636",
        "Broadway-Lafayette St": "S637",
        "Spring St (4/6)": "S638",
        "Brooklyn Bridge-City Hall": "S640",
        "Flushing-Main St": "S701",
        "Mets-Willets Point (7)": "S702",
        "111 St (7)": "S705",
        "103 St-Corona Plaza": "S706",
        "Junction Blvd": "S707",
        "90 St-Elmhurst Av": "S708",
        "82 St-Jackson Hts": "S709",
        "Jackson Hts-Roosevelt Av": "S710",
        "69 St": "S711",
        "61 St-Woodside": "S712",
        "52 St": "S713",
        "46 St-Bliss St": "S714",
        "40 St-Lowery St": "S715",
        "33 St-Rawson St": "S716",
        "Queensboro Plaza": "S718",
        "Court Sq": "S719",
        "Hunters Point Av": "S720",
        "Vernon Blvd-Jackson Av": "S721",
        "42 St-Bryant Pk": "S724",
        "34 St-Hudson Yards": "S726",
        "Inwood-207 St": "SA02",
        "190 St": "SA05",
        "175 St": "SA07",
        "163 St-Amsterdam Av": "SA10",
        "155 St": "SA11",
        "135 St (A/B/C)": "SA14",
        "116 St (A/B/C)": "SA16",
        "86 St (A/B/C)": "SA20",
        "81 St-Museum of Natural History": "SA21",
        "72 St (A/B/C)": "SA22",
        "23 St (A/C/E)": "SA30",
        "14 St (A/C/E/L)": "SA31",
        "W 4 St-Wash Sq": "SA32",
        "Spring St (A/C/E)": "SA33",
        "High St": "SA40",
        "Jay St-MetroTech": "SA41",
        "Hoyt-Schermerhorn Sts": "SA42",
        "Lafayette Av": "SA43",
        "Clinton-Washington Avs (A/C)": "SA44",
        "Franklin Av (A/C/FS)": "SA45",
        "Nostrand Av (A/C)": "SA46",
        "Kingston-Throop Avs": "SA47",
        "Utica Av": "SA48",
        "Ralph Av": "SA49",
        "Rockaway Av (A/C)": "SA50",
        "Broadway Junction": "SA51",
        "Liberty Av": "SA52",
        "Van Siclen Av (A/C)": "SA53",
        "Shepherd Av": "SA54",
        "Euclid Av": "SA55",
        "Grant Av": "SA57",
        "80 St": "SA59",
        "88 St": "SA60",
        "Rockaway Blvd": "SA61",
        "104 St (A)": "SA63",
        "111 St (A)": "SA64",
        "Ozone Park-Lefferts Blvd": "SA65",
        "21 St-Queensbridge": "SB04",
        "Roosevelt Island": "SB06",
        "57 St": "SB10",
        "9 Av": "SB12",
        "Fort Hamilton Pkwy (D)": "SB13",
        "50 St (D)": "SB14",
        "55 St": "SB15",
        "New Utrecht Av": "SB16",
        "71 St": "SB17",
        "79 St (D)": "SB18",
        "18 Av (D)": "SB19",
        "20 Av (D)": "SB20",
        "Bay Pkwy (D/R/W)": "SB21",
        "25 Av": "SB22",
        "Bay 50 St": "SB23",
        "Norwood-205 St": "SD01",
        "Bedford Park Blvd": "SD03",
        "Kingsbridge Rd (B/D)": "SD04",
        "Fordham Rd (B/D)": "SD05",
        "182-183 Sts": "SD06",
        "Tremont Av": "SD07",
        "174-175 Sts": "SD08",
        "170 St (B/D)": "SD09",
        "167 St (B/D)": "SD10",
        "7 Av (B/D/E)": "SD14",
        "47-50 Sts-Rockefeller Ctr": "SD15",
        "34 St-Herald Sq": "SD17",
        "23 St (F/M)": "SD18",
        "Grand St (B/D)": "SD22",
        "7 Av (B/Q/F/G)": "SD25",
        "Prospect Park": "SD26",
        "Parkside Av": "SD27",
        "Church Av (B/Q)": "SD28",
        "Beverley Rd": "SD29",
        "Cortelyou Rd": "SD30",
        "Newkirk Plaza": "SD31",
        "Avenue H": "SD32",
        "Avenue J": "SD33",
        "Avenue M": "SD34",
        "Kings Hwy (B/Q)": "SD35",
        "Avenue U (Q)": "SD37",
        "Neck Rd": "SD38",
        "Sheepshead Bay": "SD39",
        "Brighton Beach": "SD40",
        "Ocean Pkwy": "SD41",
        "W 8 St-NY Aquarium": "SD42",
        "Coney Island-Stillwell Av": "SD43",
        "Jamaica-179 St": "SF01",
        "169 St": "SF02",
        "Parsons Blvd": "SF03",
        "Sutphin Blvd": "SF04",
        "Briarwood": "SF05",
        "Kew Gardens-Union Tpke": "SF06",
        "75 Av": "SF07",
        "5 Av/53 St": "SF12",
        "2 Av": "SF14",
        "Delancey St-Essex St": "SF15",
        "East Broadway": "SF16",
        "York St": "SF18",
        "Bergen St (F/G)": "SF20",
        "Carroll St": "SF21",
        "Smith-9 Sts": "SF22",
        "4 Av-9 St": "SF23",
        "15 St-Prospect Park": "SF25",
        "Fort Hamilton Pkwy (F/G)": "SF26",
        "Church Av (F/G)": "SF27",
        "Ditmas Av": "SF29",
        "18 Av (F)": "SF30",
        "Avenue I": "SF31",
        "Bay Pkwy (F)": "SF32",
        "Avenue N": "SF33",
        "Avenue P": "SF34",
        "Kings Hwy (F)": "SF35",
        "Avenue U (F)": "SF36",
        "Avenue X": "SF38",
        "Neptune Av": "SF39",
        "Jamaica Center-Parsons/Archer": "SG05",
        "Sutphin Blvd-Archer Av-JFK Airport": "SG06",
        "Jamaica-Van Wyck": "SG07",
        "Forest Hills-71 Av": "SG08",
        "67 Av": "SG09",
        "63 Dr-Rego Park": "SG10",
        "Woodhaven Blvd (E/F/M/R)": "SG11",
        "Grand Av-Newtown": "SG12",
        "Elmhurst Av": "SG13",
        "65 St": "SG15",
        "Northern Blvd": "SG16",
        "46 St": "SG18",
        "Steinway St": "SG19",
        "36 St (E/F/M/R)": "SG20",
        "Queens Plaza": "SG21",
        "21 St": "SG24",
        "Greenpoint Av": "SG26",
        "Nassau Av": "SG28",
        "Metropolitan Av": "SG29",
        "Broadway (G)": "SG30",
        "Flushing Av (G)": "SG31",
        "Myrtle-Willoughby Avs": "SG32",
        "Bedford-Nostrand Avs": "SG33",
        "Classon Av": "SG34",
        "Clinton-Washington Avs (G)": "SG35",
        "Fulton St (G)": "SG36",
        "Aqueduct Racetrack": "SH01",
        "Aqueduct-N Conduit Av": "SH02",
        "Howard Beach-JFK Airport": "SH03",
        "Broad Channel": "SH04",
        "Beach 67 St": "SH06",
        "Beach 60 St": "SH07",
        "Beach 44 St": "SH08",
        "Beach 36 St": "SH09",
        "Beach 25 St": "SH10",
        "Far Rockaway-Mott Av": "SH11",
        "Beach 90 St": "SH12",
        "Beach 98 St": "SH13",
        "Beach 105 St": "SH14",
        "Rockaway Park-Beach 116 St": "SH15",
        "121 St": "SJ12",
        "111 St (J)": "SJ13",
        "104 St (J/Z)": "SJ14",
        "Woodhaven Blvd (J/Z)": "SJ15",
        "85 St-Forest Pkwy": "SJ16",
        "75 St-Elderts Ln": "SJ17",
        "Cypress Hills": "SJ19",
        "Crescent St": "SJ20",
        "Norwood Av": "SJ21",
        "Cleveland St": "SJ22",
        "Van Siclen Av (J/Z)": "SJ23",
        "Alabama Av": "SJ24",
        "Chauncey St": "SJ28",
        "Halsey St (J)": "SJ29",
        "Gates Av": "SJ30",
        "Kosciuszko St": "SJ31",
        "3 Av": "SL05",
        "1 Av": "SL06",
        "Bedford Av": "SL08",
        "Graham Av": "SL11",
        "Grand St (L)": "SL12",
        "Montrose Av": "SL13",
        "Morgan Av": "SL14",
        "Jefferson St": "SL15",
        "DeKalb Av (L)": "SL16",
        "Myrtle-Wyckoff Avs": "SL17",
        "Halsey St (L)": "SL19",
        "Wilson Av": "SL20",
        "Bushwick Av-Aberdeen St": "SL21",
        "Atlantic Av": "SL24",
        "Sutter Av": "SL25",
        "New Lots Av (L)": "SL27",
        "East 105 St": "SL28",
        "Canarsie-Rockaway Pkwy": "SL29",
        "Middle Village-Metropolitan Av": "SM01",
        "Fresh Pond Rd": "SM04",
        "Forest Av": "SM05",
        "Seneca Av": "SM06",
        "Knickerbocker Av": "SM09",
        "Central Av": "SM10",
        "Myrtle Av": "SM11",
        "Flushing Av (J/M)": "SM12",
        "Lorimer St": "SM13",
        "Hewes St": "SM14",
        "Marcy Av": "SM16",
        "Bowery": "SM19",
        "Broad St": "SM23",
        "8 Av": "SN02",
        "Fort Hamilton Pkwy (N/W)": "SN03",
        "18 Av (N/W)": "SN05",
        "20 Av (N/W)": "SN06",
        "Bay Pkwy (N/W)": "SN07",
        "Kings Hwy (N/W)": "SN08",
        "Avenue U (N/W)": "SN09",
        "86 St (N/W)": "SN10",
        "72 St (N/Q/R)": "SQ03",
        "86 St (N/Q/R)": "SQ04",
        "96 St (N/Q/R)": "SQ05",
        "Astoria-Ditmars Blvd": "SR01",
        "Astoria Blvd": "SR03",
        "30 Av": "SR04",
        "Broadway (N/W)": "SR05",
        "36 Av": "SR06",
        "39 Av-Dutch Kills": "SR08",
        "5 Av/59 St": "SR13",
        "57 St-7 Av": "SR14",
        "49 St": "SR15",
        "28 St (N/Q/R/W)": "SR18",
        "23 St (N/Q/R/W)": "SR19",
        "8 St": "SR21",
        "Prince St": "SR22",
        "City Hall": "SR24",
        "Rector St (N/R/W)": "SR26",
        "Whitehall St-South Ferry": "SR27",
        "DeKalb Av (B/D/N/Q/R/W)": "SR30",
        "Union St": "SR32",
        "Prospect Av (D/N/R/W)": "SR34",
        "25 St": "SR35",
        "36 St (D/N/R/W)": "SR36",
        "45 St": "SR39",
        "53 St": "SR40",
        "59 St": "SR41",
        "Bay Ridge Av": "SR42",
        "77 St (R)": "SR43",
        "86 St (R)": "SR44",
        "Bay Ridge-95 St": "SR45",
        "Park Pl": "SS03",
        "Tottenville": "SS09",
        "Arthur Kill": "SS11",
        "Richmond Valley": "SS13",
        "Pleasant Plains": "SS14",
        "Prince's Bay": "SS15",
        "Huguenot": "SS16",
        "Annadale": "SS17",
        "Eltingville": "SS18",
        "Great Kills": "SS19",
        "Bay Terrace": "SS20",
        "Oakwood Heights": "SS21",
        "New Dorp": "SS22",
        "Grant City": "SS23",
        "Jefferson Av": "SS24",
        "Dongan Hills": "SS25",
        "Old Town": "SS26",
        "Grasmere": "SS27",
        "Clifton (SIR)": "SS28",
        "Stapleton": "SS29",
        "Tompkinsville": "SS30",
        "St George": "SS31",

    ]

    /// Reverse lookup dictionary: code → canonical station name.
    /// This provides O(1) lookup for displaying station names from codes.
    /// Includes equivalent Amtrak codes for stations shared with Metro-North,
    /// so that API responses using either code resolve to the correct display name.
    static let stationCodeToName: [String: String] = {
        var result: [String: String] = [:]
        for (name, code) in stationCodes {
            result[code] = name
        }
        // Map equivalent Amtrak codes to the same station name.
        // These stations are shared between Amtrak and Metro-North but use
        // different internal codes. The stationCodes dict uses MNR codes;
        // these entries ensure Amtrak codes also resolve correctly.
        let amtrakEquivalents: [(amtrakCode: String, mnrCode: String)] = [
            ("YNY", "MYON"),   // Yonkers
            ("CRT", "MCRH"),   // Croton-Harmon
            ("POU", "MPOK"),   // Poughkeepsie
            ("NRO", "MNRC"),   // New Rochelle
            ("STM", "MSTM"),   // Stamford
            ("BRP", "MBGP"),   // Bridgeport
            ("NHV", "MNHV"),   // New Haven
            ("STS", "MNSS"),   // New Haven-State St
        ]
        for (amtrakCode, mnrCode) in amtrakEquivalents {
            if let name = result[mnrCode] {
                result[amtrakCode] = name
            }
        }
        // Map equivalent subway complex codes to the same station name.
        // These station complexes share physical transfer connections but use
        // different internal codes per platform. The stationCodes dict uses the
        // canonical (first sorted) code; these ensure all codes resolve correctly.
        let subwayComplexEquivalents: [(alternateCode: String, canonicalCode: String)] = [
            ("SA03", "S109"),  // Dyckman St
            ("SA06", "S111"),  // 181 St
            ("SA09", "S112"),  // 168 St
            ("S302", "S114"),  // 145 St
            ("SA12", "S114"),  // 145 St
            ("SD13", "S114"),  // 145 St
            ("S225", "S116"),  // 125 St
            ("S621", "S116"),  // 125 St
            ("SA15", "S116"),  // 125 St
            ("SA17", "S118"),  // Cathedral Pkwy (110 St)
            ("SA18", "S119"),  // 103 St (1/A/B/C)
            ("SA19", "S120"),  // 96 St (1/2/3/A/B/C)
            ("SA24", "S125"),  // 59 St-Columbus Circle
            ("SA25", "S126"),  // 50 St (1/2/A/C/E)
            ("S725", "S127"),  // Times Sq-42 St
            ("S902", "S127"),  // Times Sq-42 St
            ("SA27", "S127"),  // Times Sq-42 St
            ("SR16", "S127"),  // Times Sq-42 St
            ("SA28", "S128"),  // 34 St-Penn Station
            ("SD19", "S132"),  // 14 St (1/2/3/F/L/M)
            ("SL02", "S132"),  // 14 St (1/2/3/F/L/M)
            ("S639", "S135"),  // Canal St
            ("SA34", "S135"),  // Canal St
            ("SM20", "S135"),  // Canal St
            ("SQ01", "S135"),  // Canal St
            ("SR23", "S135"),  // Canal St
            ("S138", "S228"),  // Chambers St-WTC
            ("SA36", "S228"),  // Chambers St-WTC
            ("SE01", "S228"),  // Chambers St-WTC
            ("SR25", "S228"),  // Chambers St-WTC
            ("S503", "S208"),  // Gun Hill Rd
            ("S504", "S211"),  // Pelham Pkwy
            ("S415", "S222"),  // 149 St-Grand Concourse
            ("S418", "S229"),  // Fulton St (2/3/4/5/A/C/J/Z)
            ("SA38", "S229"),  // Fulton St (2/3/4/5/A/C/J/Z)
            ("SM22", "S229"),  // Fulton St (2/3/4/5/A/C/J/Z)
            ("S423", "S232"),  // Borough Hall
            ("SR28", "S232"),  // Borough Hall
            ("SD24", "S235"),  // Atlantic Av-Barclays Ctr
            ("SR31", "S235"),  // Atlantic Av-Barclays Ctr
            ("SS04", "S239"),  // Franklin Av (2/3/4/5/FS)
            ("SL26", "S254"),  // Livonia Av
            ("SD11", "S414"),  // 161 St-Yankee Stadium
            ("SB08", "S629"),  // Lexington Av/59 St
            ("SR11", "S629"),  // Lexington Av/59 St
            ("SF11", "S630"),  // Lexington Av/53 St
            ("S723", "S631"),  // Grand Central-42 St
            ("S901", "S631"),  // Grand Central-42 St
            ("SL03", "S635"),  // 14 St-Union Sq
            ("SR20", "S635"),  // 14 St-Union Sq
            ("SD21", "S637"),  // Broadway-Lafayette St
            ("SM21", "S640"),  // Brooklyn Bridge-City Hall
            ("SG14", "S710"),  // Jackson Hts-Roosevelt Av
            ("SR09", "S718"),  // Queensboro Plaza
            ("SF09", "S719"),  // Court Sq
            ("SG22", "S719"),  // Court Sq
            ("SD16", "S724"),  // 42 St-Bryant Pk
            ("SD12", "SA11"),  // 155 St
            ("SL01", "SA31"),  // 14 St (A/C/E/L)
            ("SD20", "SA32"),  // W 4 St-Wash Sq
            ("SR29", "SA41"),  // Jay St-MetroTech
            ("SS01", "SA45"),  // Franklin Av (A/C/FS)
            ("SJ27", "SA51"),  // Broadway Junction
            ("SL22", "SA51"),  // Broadway Junction
            ("SN04", "SB16"),  // New Utrecht Av
            ("SR17", "SD17"),  // 34 St-Herald Sq
            ("SF24", "SD25"),  // 7 Av (B/Q/F/G)
            ("SM18", "SF15"),  // Delancey St-Essex St
            ("SR33", "SF23"),  // 4 Av-9 St
            ("SL10", "SG29"),  // Metropolitan Av
            ("SM08", "SL17"),  // Myrtle-Wyckoff Avs
        ]
        for (alternateCode, canonicalCode) in subwayComplexEquivalents {
            if let name = result[canonicalCode] {
                result[alternateCode] = name
            }
        }
        return result
    }()

    /// Returns the full station name for a given station code.
    /// Example: stationName(forCode: "NY") returns "New York Penn Station"
    static func stationName(forCode code: String) -> String? {
        return stationCodeToName[code]
    }

    // MARK: - Station Code Equivalence

    /// Maps each station code to the set of all equivalent codes (including itself).
    /// Built from cross-system (Amtrak/MNR) and subway complex equivalences.
    static let stationEquivalents: [String: Set<String>] = {
        var groups: [Set<String>] = [
            // Cross-system: Amtrak / Metro-North shared stations
            ["NRO", "MNRC"],   // New Rochelle
            ["YNY", "MYON"],   // Yonkers
            ["CRT", "MCRH"],   // Croton-Harmon
            ["POU", "MPOK"],   // Poughkeepsie
            ["STM", "MSTM"],   // Stamford
            ["BRP", "MBGP"],   // Bridgeport
            ["NHV", "MNHV"],   // New Haven
            ["STS", "MNSS"],   // New Haven-State St
        ]

        // Subway station complexes: build groups from (alternate, canonical) pairs
        let subwayPairs: [(String, String)] = [
            ("SA03", "S109"),  ("SA06", "S111"),  ("SA09", "S112"),
            ("S302", "S114"),  ("SA12", "S114"),  ("SD13", "S114"),
            ("S225", "S116"),  ("S621", "S116"),  ("SA15", "S116"),
            ("SA17", "S118"),  ("SA18", "S119"),  ("SA19", "S120"),
            ("SA24", "S125"),  ("SA25", "S126"),  ("S725", "S127"),
            ("S902", "S127"),  ("SA27", "S127"),  ("SR16", "S127"),
            ("SA28", "S128"),  ("SD19", "S132"),  ("SL02", "S132"),
            ("S639", "S135"),  ("SA34", "S135"),  ("SM20", "S135"),
            ("SQ01", "S135"),  ("SR23", "S135"),
            ("S138", "S228"),  ("SA36", "S228"),  ("SE01", "S228"),
            ("SR25", "S228"),  ("PWC", "S228"),   // PATH WTC ↔ Subway WTC (Oculus)
            ("S503", "S208"),  ("S504", "S211"),
            ("S415", "S222"),
            ("S418", "S229"),  ("SA38", "S229"),  ("SM22", "S229"),
            ("S423", "S232"),  ("SR28", "S232"),  ("SD24", "S235"),
            ("SR31", "S235"),  ("SS04", "S239"),  ("SL26", "S254"),
            ("SD11", "S414"),  ("SB08", "S629"),  ("SR11", "S629"),
            ("SF11", "S630"),  ("S723", "S631"),  ("S901", "S631"),
            ("SL03", "S635"),  ("SR20", "S635"),  ("SD21", "S637"),
            ("SM21", "S640"),  ("SG14", "S710"),  ("SR09", "S718"),
            ("SF09", "S719"),  ("SG22", "S719"),  ("SD16", "S724"),
            ("SD12", "SA11"),  ("SL01", "SA31"),  ("SD20", "SA32"),
            ("SR29", "SA41"),  ("SS01", "SA45"),  ("SJ27", "SA51"),
            ("SL22", "SA51"),  ("SN04", "SB16"),  ("SR17", "SD17"),
            ("SF24", "SD25"),  ("SM18", "SF15"),  ("SR33", "SF23"),
            ("SL10", "SG29"),  ("SM08", "SL17"),
        ]
        // Merge pairs into groups (a canonical code may appear multiple times)
        var canonicalToIndex: [String: Int] = [:]
        for (alternate, canonical) in subwayPairs {
            if let idx = canonicalToIndex[canonical] {
                groups[idx].insert(alternate)
            } else {
                let idx = groups.count
                groups.append([canonical, alternate])
                canonicalToIndex[canonical] = idx
            }
        }

        // Build the lookup: each code maps to its full group
        var result: [String: Set<String>] = [:]
        for group in groups {
            for code in group {
                result[code] = group
            }
        }
        return result
    }()
}
